<template>
  <div ref="boxRef" role="img" :aria-label="playlist.name" class="h-full w-full">
    <canvas v-if="!failed" ref="canvasRef" class="block h-full w-full" aria-hidden="true" />
    <div v-else class="flex h-full w-full items-center justify-center">
      <UIcon name="mdi:playlist-music" class="h-10 w-10 text-gray-300 dark:text-white/20" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from "vue";

import type { AutoGroupKind } from "@/enums/auto-group-kind";

import { useTheme } from "@/composables/useTheme";
import {
  coverLayoutFor,
  coverPalette,
  decadeDigits,
  monogramFor,
  moodGlyphFor,
  type CoverLayout,
  type MoodGlyph,
} from "@/utils/playlist-cover.utils";

const props = defineProps<{
  playlist: {
    id: string;
    name: string;
    isAutoGenerated: boolean;
    autoGroupKind: AutoGroupKind | null;
  };
}>();

const ARTIST_ALBUM_LAYOUT: CoverLayout = "monogram";
const FONT_STACK = 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';

const boxRef = ref<HTMLDivElement | null>(null);
const canvasRef = ref<HTMLCanvasElement | null>(null);
const failed = ref(false);
const painted = ref(false);

const { isDark } = useTheme();

// Hash + palette

const hashString = (s: string) => {
  let h = 2166136261 >>> 0;
  for (let i = 0; i < s.length; i += 1) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
};

type PrintPalette = {
  paper: string;
  anchor: string;
  inks: [string, string, string];
  blendMode: GlobalCompositeOperation;
};

// Hand-picked riso-ish accents used when a card has no detected mood
// (decade, genre, monogram), so two IDs with similar base hues still
// diverge from each other.
const RISO_ACCENTS = [330, 195, 45, 260, 10, 150] as const;

// Color-theory palettes for the mood layout. Hues, saturation and a
// lightness offset ("warmth") are curated per emotion rather than
// hashed, so a happy playlist actually looks happy and a sad one
// actually looks sad, instead of both landing on whatever hue the id
// happened to hash to.
type MoodTheory = {
  hues: [number, number, number];
  saturation: number;
  warmth: number;
};

const MOOD_COLOR_THEORY: Partial<Record<MoodGlyph, MoodTheory>> = {
  // happy: sunflower, warm coral, fresh green
  sun: { hues: [45, 350, 110], saturation: 82, warmth: 8 },
  // sad: rain blue, muted indigo, slate teal
  droplet: { hues: [215, 250, 195], saturation: 42, warmth: -10 },
  // calm: soft teal, lavender, sage
  horizon: { hues: [178, 258, 140], saturation: 38, warmth: 0 },
  // party: magenta, electric cyan, sunflower
  confetti: { hues: [330, 185, 50], saturation: 85, warmth: 6 },
  // hype: fire orange, electric yellow, deep magenta
  burst: { hues: [12, 55, 320], saturation: 88, warmth: 10 },
  // acoustic: amber, terracotta, moss
  soundhole: { hues: [30, 15, 95], saturation: 52, warmth: -2 },
};

// oxlint-disable-next-line max-statements
const printPalette = (id: string, isDark: boolean, moodGlyph: MoodGlyph | null): PrintPalette => {
  const seed = hashString(id);
  const theory = moodGlyph ? MOOD_COLOR_THEORY[moodGlyph] : undefined;

  let hueA: number;
  let hueB: number;
  let hueC: number;
  let saturation: number;
  let warmth: number;

  if (theory) {
    [hueA, hueB, hueC] = theory.hues;
    saturation = theory.saturation;
    warmth = theory.warmth;
  } else {
    const base = coverPalette(id, isDark);
    hueA = base.hue;
    hueB = RISO_ACCENTS[(seed >>> 8) % RISO_ACCENTS.length];
    hueC = (base.hue + 200) % 360;
    saturation = 76;
    warmth = 0;
  }

  // Cream stock in light mode, a soft charcoal (not pure black) in dark
  // mode. A near-black backdrop leaves no headroom for "screen" to
  // brighten into.
  const paper = isDark ? "#1a1b1f" : "#f1e7d3";
  const anchor = isDark ? "#f1e7d3" : "#12100e";

  // Multiply darkens toward the base, so it needs a light base to read
  // as pigment. Screen brightens toward white, so it needs a dark base
  // instead.
  const blendMode: GlobalCompositeOperation = isDark ? "screen" : "multiply";

  const lA = (isDark ? 46 : 52) + warmth;
  const lB = (isDark ? 42 : 50) + warmth;
  const lC = (isDark ? 38 : 44) + warmth;

  const inkA = `hsl(${hueA} ${saturation}% ${lA}%)`;
  const inkB = `hsl(${hueB} ${Math.max(saturation - 2, 0)}% ${lB}%)`;
  const inkC = `hsl(${hueC} ${Math.max(saturation - 6, 0)}% ${lC}%)`;

  return { paper, anchor, inks: [inkA, inkB, inkC], blendMode };
};

// Lazy paint observer (unchanged)

let sharedObserver: IntersectionObserver | null = null;
const pendingPaints = new WeakMap<Element, () => void>();

const getObserver = () => {
  if (sharedObserver) return sharedObserver;
  sharedObserver = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting) {
          pendingPaints.get(entry.target)?.();
          sharedObserver?.unobserve(entry.target);
        }
      }
    },
    { rootMargin: "200px" },
  );
  return sharedObserver;
};

let resizeObserver: ResizeObserver | null = null;
let lastSize = 0;

// Texture caches

let grainTile: HTMLCanvasElement | null = null;
const getGrainTile = () => {
  if (grainTile) return grainTile;
  const tile = document.createElement("canvas");
  tile.width = 64;
  tile.height = 64;
  const tctx = tile.getContext("2d");
  if (tctx) {
    const img = tctx.createImageData(64, 64);
    for (let i = 0; i < img.data.length; i += 4) {
      const v = Math.random() * 255;
      img.data[i] = v;
      img.data[i + 1] = v;
      img.data[i + 2] = v;
      img.data[i + 3] = 255;
    }
    tctx.putImageData(img, 0, 0);
  }
  grainTile = tile;
  return tile;
};

const dotTiles: Record<string, HTMLCanvasElement> = {};
const getDotTile = (paper: string) => {
  if (dotTiles[paper]) return dotTiles[paper];
  const tile = document.createElement("canvas");
  tile.width = 5;
  tile.height = 5;
  const tctx = tile.getContext("2d");
  if (tctx) {
    tctx.fillStyle = paper;
    tctx.beginPath();
    tctx.arc(2.5, 2.5, 1.15, 0, Math.PI * 2);
    tctx.fill();
  }
  dotTiles[paper] = tile;
  return tile;
};

const paintGrain = (ctx: CanvasRenderingContext2D, size: number, isDark: boolean) => {
  const pattern = ctx.createPattern(getGrainTile(), "repeat");
  if (!pattern) return;
  ctx.save();
  ctx.globalAlpha = isDark ? 0.03 : 0.045;
  ctx.fillStyle = pattern;
  ctx.fillRect(0, 0, size, size);
  ctx.restore();
};

// oxlint-disable-next-line max-params
const paintHalftone = (
  ctx: CanvasRenderingContext2D,
  size: number,
  paper: string,
  isDark: boolean,
) => {
  const pattern = ctx.createPattern(getDotTile(paper), "repeat");
  if (!pattern) return;
  ctx.save();
  ctx.globalAlpha = isDark ? 0.14 : 0.22;
  ctx.fillStyle = pattern;
  ctx.fillRect(0, 0, size, size);
  ctx.restore();
};

// Misregistration helper, deterministic per (id, layer)
// oxlint-disable-next-line max-params
const withJitter = (
  ctx: CanvasRenderingContext2D,
  seed: number,
  layer: number,
  size: number,
  draw: () => void,
) => {
  const s = (seed ^ (layer * 2654435761)) >>> 0;
  const dx = ((s & 0xff) / 255 - 0.5) * size * 0.025;
  const dy = (((s >>> 8) & 0xff) / 255 - 0.5) * size * 0.025;
  ctx.save();
  ctx.translate(dx, dy);
  draw();
  ctx.restore();
};

const paintBackdrop = (ctx: CanvasRenderingContext2D, palette: PrintPalette, size: number) => {
  ctx.fillStyle = palette.paper;
  ctx.fillRect(0, 0, size, size);
};

const paintInkShapes = (
  ctx: CanvasRenderingContext2D,
  layout: CoverLayout,
  palette: PrintPalette,
  size: number,
  seed: number,
) => {
  const [inkA, inkB, inkC] = palette.inks;

  ctx.save();
  ctx.globalCompositeOperation = palette.blendMode;

  if (layout === "decade") {
    withJitter(ctx, seed, 0, size, () => {
      ctx.fillStyle = inkA;
      ctx.beginPath();
      ctx.arc(size * 0.82, size * 0.22, size * 0.55, 0, Math.PI * 2);
      ctx.fill();
    });
    withJitter(ctx, seed, 1, size, () => {
      ctx.fillStyle = inkB;
      ctx.fillRect(-size * 0.05, size * 0.74, size * 1.1, size * 0.32);
    });
    withJitter(ctx, seed, 2, size, () => {
      ctx.fillStyle = inkC;
      ctx.beginPath();
      ctx.arc(size * 0.16, size * 0.14, size * 0.09, 0, Math.PI * 2);
      ctx.fill();
    });
  } else if (layout === "mood") {
    withJitter(ctx, seed, 0, size, () => {
      ctx.fillStyle = inkA;
      ctx.beginPath();
      ctx.arc(size * 0.5, size * 0.42, size * 0.42, 0, Math.PI * 2);
      ctx.fill();
    });
    withJitter(ctx, seed, 1, size, () => {
      ctx.fillStyle = inkB;
      ctx.beginPath();
      ctx.moveTo(-size * 0.05, size * 1.05);
      ctx.lineTo(size * 0.5, size * 0.55);
      ctx.lineTo(size * 1.05, size * 1.05);
      ctx.closePath();
      ctx.fill();
    });
  } else if (layout === "monogram") {
    withJitter(ctx, seed, 0, size, () => {
      ctx.fillStyle = inkA;
      ctx.beginPath();
      ctx.arc(size * 0.18, size * 0.18, size * 0.55, 0, Math.PI * 2);
      ctx.fill();
    });
    withJitter(ctx, seed, 1, size, () => {
      ctx.fillStyle = inkB;
      ctx.beginPath();
      ctx.moveTo(size * 1.05, size * 0.32);
      ctx.lineTo(size * 1.05, size * 0.58);
      ctx.lineTo(size * 0.32, size * 1.05);
      ctx.lineTo(size * 0.08, size * 1.05);
      ctx.closePath();
      ctx.fill();
    });
  } else {
    // Genre / wordmark fallback. Widened from the original 36-64%
    // band so a two-line title has room to cross both the top and
    // bottom paper/ink seam, not just sit inside a thin strip.
    withJitter(ctx, seed, 0, size, () => {
      ctx.fillStyle = inkA;
      ctx.fillRect(-size * 0.02, size * 0.32, size * 1.04, size * 0.36);
    });
    withJitter(ctx, seed, 1, size, () => {
      ctx.fillStyle = inkB;
      ctx.beginPath();
      ctx.arc(size * 0.87, size * 0.85, size * 0.19, 0, Math.PI * 2);
      ctx.fill();
    });
  }

  ctx.restore();
};

// Typography

// Draws each character with an optional stroke "halo" behind the fill.
// The halo should always be the opposite tone from the fill (paper
// behind anchor-colored text, or anchor behind paper-colored text) so
// the label stays legible no matter what ink shapes sit underneath it,
// including multiply/screen overlap seams that land darker or lighter
// than either input color alone.
const fillTextSpaced = (
  ctx: CanvasRenderingContext2D,
  text: string,
  cx: number,
  cy: number,
  spacing: number,
  haloColor?: string,
  haloWidth?: number,
) => {
  const chars = text.split("");
  const widths = chars.map((ch) => ctx.measureText(ch).width);
  const total = widths.reduce((a, b) => a + b, 0) + spacing * (chars.length - 1);
  let x = cx - total / 2;
  const prevAlign = ctx.textAlign;
  ctx.textAlign = "left";
  for (let i = 0; i < chars.length; i += 1) {
    if (haloColor) {
      ctx.save();
      ctx.strokeStyle = haloColor;
      ctx.lineWidth = haloWidth ?? 4;
      ctx.lineJoin = "round";
      ctx.strokeText(chars[i], x, cy);
      ctx.restore();
    }
    ctx.fillText(chars[i], x, cy);
    x += widths[i] + spacing;
  }
  ctx.textAlign = prevAlign;
};

// oxlint-disable-next-line max-params
const fillTextHalo = (
  ctx: CanvasRenderingContext2D,
  text: string,
  cx: number,
  cy: number,
  haloColor: string,
  haloWidth: number,
) => {
  ctx.save();
  ctx.strokeStyle = haloColor;
  ctx.lineWidth = haloWidth;
  ctx.lineJoin = "round";
  ctx.strokeText(text, cx, cy);
  ctx.restore();
  ctx.fillText(text, cx, cy);
};

// oxlint-disable-next-line max-params
const fitFont = (
  ctx: CanvasRenderingContext2D,
  text: string,
  maxWidth: number,
  base: number,
  weight: number,
) => {
  let size = base;
  while (size > base * 0.3) {
    ctx.font = `${weight} ${size}px ${FONT_STACK}`;
    if (ctx.measureText(text).width <= maxWidth) return;
    size *= 0.92;
  }
};

// Same as fitFont, but shrinks against the widest of several lines so
// they can share one consistent font size.
const fitFontMulti = (
  ctx: CanvasRenderingContext2D,
  lines: string[],
  maxWidth: number,
  base: number,
  weight: number,
) => {
  let size = base;
  while (size > base * 0.3) {
    ctx.font = `${weight} ${size}px ${FONT_STACK}`;
    const widest = Math.max(...lines.map((line) => ctx.measureText(line).width));
    if (widest <= maxWidth) return;
    size *= 0.92;
  }
};

// Splits a title into two roughly width-balanced lines at a word
// boundary. Single-word titles are returned as-is with an empty
// second line, the caller falls back to single-line rendering.
const splitTitleLines = (ctx: CanvasRenderingContext2D, text: string): [string, string] => {
  const words = text.split(/\s+/).filter(Boolean);
  if (words.length <= 1) return [text, ""];

  ctx.font = `900 100px ${FONT_STACK}`;
  const widths = words.map((w) => ctx.measureText(`${w} `).width);
  const total = widths.reduce((a, b) => a + b, 0);

  let bestSplit = 1;
  let bestDiff = Infinity;
  let running = 0;
  for (let i = 0; i < words.length - 1; i += 1) {
    running += widths[i];
    const diff = Math.abs(running - (total - running));
    if (diff < bestDiff) {
      bestDiff = diff;
      bestSplit = i + 1;
    }
  }

  return [words.slice(0, bestSplit).join(" "), words.slice(bestSplit).join(" ")];
};

// Silhouette glyphs, filled shapes rather than line art

// oxlint-disable-next-line max-statements max-lines-per-function max-params
const paintGlyph = (
  ctx: CanvasRenderingContext2D,
  glyph: MoodGlyph,
  cx: number,
  cy: number,
  s: number,
  ink: string,
) => {
  ctx.save();
  ctx.fillStyle = ink;
  ctx.strokeStyle = ink;
  ctx.lineCap = "round";
  ctx.lineJoin = "round";

  if (glyph === "burst") {
    ctx.beginPath();
    const spikes = 8;
    for (let i = 0; i <= spikes * 2; i += 1) {
      const angle = (i / (spikes * 2)) * Math.PI * 2 - Math.PI / 2;
      const r = i % 2 === 0 ? s : s * 0.5;
      const x = cx + Math.cos(angle) * r;
      const y = cy + Math.sin(angle) * r;
      if (i === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    }
    ctx.closePath();
    ctx.fill();
  } else if (glyph === "sun") {
    ctx.beginPath();
    ctx.arc(cx, cy, s * 0.32, 0, Math.PI * 2);
    ctx.fill();
    ctx.lineWidth = Math.max(3, s * 0.08);
    for (let i = 0; i < 8; i += 1) {
      const angle = (i / 8) * Math.PI * 2;
      ctx.beginPath();
      ctx.moveTo(cx + Math.cos(angle) * s * 0.5, cy + Math.sin(angle) * s * 0.5);
      ctx.lineTo(cx + Math.cos(angle) * s * 0.78, cy + Math.sin(angle) * s * 0.78);
      ctx.stroke();
    }
  } else if (glyph === "confetti") {
    const dots: [number, number, number][] = [
      [-0.42, -0.36, 0.1],
      [0.08, -0.5, 0.14],
      [0.46, -0.18, 0.09],
      [-0.16, 0.06, 0.12],
      [0.36, 0.3, 0.11],
      [-0.46, 0.42, 0.08],
      [0.04, 0.5, 0.13],
      [-0.02, -0.14, 0.07],
    ];
    for (const [dx, dy, r] of dots) {
      ctx.beginPath();
      ctx.arc(cx + dx * s, cy + dy * s, r * s, 0, Math.PI * 2);
      ctx.fill();
    }
  } else if (glyph === "horizon") {
    ctx.beginPath();
    ctx.arc(cx, cy - s * 0.26, s * 0.26, 0, Math.PI * 2);
    ctx.fill();
    for (let i = 0; i < 3; i += 1) {
      const y = cy + s * (0.14 + i * 0.19);
      const w = s * (0.68 - i * 0.1);
      const h = s * 0.09;
      ctx.fillRect(cx - w, y - h / 2, w * 2, h);
    }
  } else if (glyph === "droplet") {
    ctx.beginPath();
    ctx.moveTo(cx, cy - s * 0.55);
    ctx.bezierCurveTo(
      cx + s * 0.45,
      cy - s * 0.05,
      cx + s * 0.36,
      cy + s * 0.42,
      cx,
      cy + s * 0.42,
    );
    ctx.bezierCurveTo(
      cx - s * 0.36,
      cy + s * 0.42,
      cx - s * 0.45,
      cy - s * 0.05,
      cx,
      cy - s * 0.55,
    );
    ctx.closePath();
    ctx.fill();
  } else if (glyph === "soundhole") {
    ctx.beginPath();
    ctx.arc(cx, cy, s * 0.44, 0, Math.PI * 2);
    ctx.arc(cx, cy, s * 0.2, 0, Math.PI * 2, true);
    ctx.fill("evenodd");
  } else if (glyph === "note") {
    ctx.beginPath();
    ctx.ellipse(cx - s * 0.15, cy + s * 0.32, s * 0.24, s * 0.18, -0.28, 0, Math.PI * 2);
    ctx.fill();
    ctx.lineWidth = s * 0.1;
    ctx.beginPath();
    ctx.moveTo(cx + s * 0.06, cy + s * 0.3);
    ctx.lineTo(cx + s * 0.06, cy - s * 0.5);
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(cx + s * 0.06, cy - s * 0.5);
    ctx.lineTo(cx + s * 0.46, cy - s * 0.38);
    ctx.lineTo(cx + s * 0.06, cy - s * 0.24);
    ctx.closePath();
    ctx.fill();
  } else {
    ctx.lineWidth = Math.max(3, s * 0.07);
    for (let i = 0; i < 3; i += 1) {
      ctx.beginPath();
      ctx.arc(cx - s * 0.25, cy, s * (0.22 + i * 0.2), -Math.PI / 3, Math.PI / 3);
      ctx.stroke();
    }
    ctx.beginPath();
    ctx.arc(cx - s * 0.25, cy, s * 0.09, 0, Math.PI * 2);
    ctx.fill();
  }

  ctx.restore();
};

// Content painters, one poster layout per kind

const paintDecade = (ctx: CanvasRenderingContext2D, palette: PrintPalette, size: number) => {
  const digits = decadeDigits(props.playlist.name) ?? "";

  ctx.strokeStyle = palette.anchor;
  ctx.lineJoin = "round";
  ctx.lineWidth = Math.max(4, size * 0.016);
  fitFont(ctx, digits, size * 0.86, size * 0.42, 900);
  ctx.strokeText(digits, size / 2, size * 0.44);

  ctx.strokeStyle = palette.anchor;
  ctx.lineWidth = Math.max(1.5, size * 0.006);
  ctx.beginPath();
  ctx.moveTo(size * 0.32, size * 0.66);
  ctx.lineTo(size * 0.68, size * 0.66);
  ctx.stroke();

  ctx.fillStyle = palette.anchor;
  fitFont(ctx, "THE SOUND OF", size * 0.5, size * 0.058, 700);
  fillTextSpaced(ctx, "THE SOUND OF", size / 2, size * 0.82, size * 0.024);
};

const paintMonogram = (ctx: CanvasRenderingContext2D, palette: PrintPalette, size: number) => {
  const initials = monogramFor(props.playlist.name);
  const label = props.playlist.name.toUpperCase();
  const haloWidth = Math.max(2, size * 0.012);

  // Both sit on top of the large cropped circle, so both get a halo.
  ctx.fillStyle = palette.anchor;
  fitFont(ctx, label, size * 0.6, size * 0.05, 700);
  fillTextSpaced(ctx, label, size / 2, size * 0.16, size * 0.024, palette.paper, haloWidth);

  ctx.fillStyle = palette.anchor;
  fitFont(ctx, initials, size * 0.7, size * 0.44, 900);
  fillTextHalo(ctx, initials, size / 2, size * 0.56, palette.paper, haloWidth * 1.5);
};

const paintMood = (
  ctx: CanvasRenderingContext2D,
  palette: PrintPalette,
  size: number,
  glyph: MoodGlyph,
) => {
  const label = props.playlist.name.toUpperCase();
  const haloWidth = Math.max(2, size * 0.012);

  paintGlyph(ctx, glyph, size * 0.5, size * 0.42, size * 0.26, palette.anchor);

  // This label sits right on the circle/triangle overlap seam, exactly
  // where multiply or screen blending can push the result surprisingly
  // dark or light. The halo is what keeps it readable there.
  ctx.fillStyle = palette.anchor;
  fitFont(ctx, label, size * 0.78, size * 0.088, 800);
  fillTextSpaced(ctx, label, size / 2, size * 0.82, size * 0.024, palette.paper, haloWidth);
};

const paintDefault = (ctx: CanvasRenderingContext2D, palette: PrintPalette, size: number) => {
  const label = props.playlist.name.toUpperCase();
  const haloWidth = Math.max(2, size * 0.012);
  const [line1, line2] = splitTitleLines(ctx, label);

  ctx.fillStyle = palette.paper;

  if (line2) {
    fitFontMulti(ctx, [line1, line2], size * 0.86, size * 0.15, 900);
    fillTextSpaced(ctx, line1, size / 2, size * 0.42, size * 0.006, palette.anchor, haloWidth);
    fillTextSpaced(ctx, line2, size / 2, size * 0.58, size * 0.006, palette.anchor, haloWidth);
  } else {
    fitFont(ctx, line1, size * 0.82, size * 0.18, 900);
    fillTextSpaced(ctx, line1, size / 2, size * 0.5, size * 0.008, palette.anchor, haloWidth);
  }
};

// Master paint

// oxlint-disable-next-line max-statements
const paint = () => {
  const box = boxRef.value;
  const canvas = canvasRef.value;
  if (!box || !canvas || failed.value) return;

  const rect = box.getBoundingClientRect();
  const cssSize = Math.floor(Math.min(rect.width, rect.height));
  if (cssSize < 8) return;

  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  canvas.width = cssSize * dpr;
  canvas.height = cssSize * dpr;

  const ctx = canvas.getContext("2d");
  if (!ctx) {
    failed.value = true;
    return;
  }

  const dark = isDark.value;
  const layout = coverLayoutFor(
    props.playlist.isAutoGenerated,
    props.playlist.autoGroupKind,
    props.playlist.name,
    ARTIST_ALBUM_LAYOUT,
  );
  const moodGlyph = layout === "mood" ? (moodGlyphFor(props.playlist.name) ?? "sun") : null;
  const palette = printPalette(props.playlist.id, dark, moodGlyph);
  const seed = hashString(props.playlist.id);
  const size = cssSize * dpr;

  paintBackdrop(ctx, palette, size);
  paintInkShapes(ctx, layout, palette, size, seed);
  paintHalftone(ctx, size, palette.paper, dark);
  paintGrain(ctx, size, dark);

  ctx.textAlign = "center";
  ctx.textBaseline = "middle";

  if (layout === "decade") paintDecade(ctx, palette, size);
  else if (layout === "monogram") paintMonogram(ctx, palette, size);
  else if (layout === "mood") paintMood(ctx, palette, size, moodGlyph ?? "sun");
  else paintDefault(ctx, palette, size);

  lastSize = cssSize;
  painted.value = true;
};

// Lazy paint plumbing (unchanged)

const requestPaint = () => {
  const box = boxRef.value;
  if (!box || painted.value) return;
  if (typeof IntersectionObserver === "undefined") {
    paint();
    return;
  }
  pendingPaints.set(box, paint);
  getObserver().observe(box);
};

onMounted(() => {
  requestPaint();
  const box = boxRef.value;
  if (box && typeof ResizeObserver !== "undefined") {
    resizeObserver = new ResizeObserver(() => {
      if (!painted.value) return;
      const rect = box.getBoundingClientRect();
      const cssSize = Math.floor(Math.min(rect.width, rect.height));
      if (Math.abs(cssSize - lastSize) > 2) paint();
    });
    resizeObserver.observe(box);
  }
});

onUnmounted(() => {
  const box = boxRef.value;
  if (box) {
    sharedObserver?.unobserve(box);
    pendingPaints.delete(box);
  }
  resizeObserver?.disconnect();
  resizeObserver = null;
});

watch(isDark, () => {
  if (painted.value) paint();
});

watch(
  () => props.playlist.id,
  () => {
    painted.value = false;
    failed.value = false;
    lastSize = 0;
    requestPaint();
  },
);
</script>
