# prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "garage"
    static_configs:
      - targets: ["garage:3903"]
    authorization:
      type: Bearer
      credentials: "Your super secret token goes here"
