<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AwesomeAssertions"/>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NSubstitute"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Alexandria.Services.Storage\Alexandria.Services.Storage.csproj"/>
        <ProjectReference Include="..\Alexandria.Services.Streaming\Alexandria.Services.Streaming.csproj"/>
        <ProjectReference Include="..\Alexandria.Workers.Lyrics\Alexandria.Workers.Lyrics.csproj"/>
        <ProjectReference Include="..\Alexandria.Common\Alexandria.Common.csproj"/>
        <ProjectReference Include="..\Alexandria.Data.Models\Alexandria.Data.Models.csproj"/>
        <ProjectReference Include="..\Alexandria.Dto\Alexandria.Dto.csproj"/>
        <ProjectReference Include="..\Alexandria.Repositories\Alexandria.Repositories.csproj"/>
        <ProjectReference Include="..\Alexandria.Tests.Common\Alexandria.Tests.Common.csproj"/>
    </ItemGroup>

</Project>