using Alexandria.Common;
using Alexandria.Common.Repositories;
using Alexandria.Common.Services;
using Alexandria.Common.Settings.Values;
using Alexandria.Data.Models;
using Alexandria.Data.Models.Enumerators;
using Alexandria.Dto.Files.Streaming.Playlist;
using Alexandria.Services.Streaming;
using AwesomeAssertions;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;
using NSubstitute;

namespace Alexandria.Tests.Unit.Streaming;

public class AutoPlaylistSyncServiceTests
{
    private static readonly Guid Owner = Guid.Parse("cccccccc-cccc-cccc-cccc-cccccccccccc");
    private static readonly Guid FileOne = Guid.Parse("11111111-1111-1111-1111-111111111111");
    private static readonly Guid FileTwo = Guid.Parse("22222222-2222-2222-2222-222222222222");
    private static readonly Guid JobOne = Guid.Parse("33333333-3333-3333-3333-333333333333");
    private static readonly Guid PlaylistId = Guid.Parse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa");
    private static readonly Guid ItemId = Guid.Parse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb");

    private readonly IUnitOfWork _unitOfWork = Substitute.For<IUnitOfWork>();
    private readonly IPlaylistRepository _playlists = Substitute.For<IPlaylistRepository>();
    private readonly IJobRepository _jobs = Substitute.For<IJobRepository>();
    private readonly ITagRepository _tags = Substitute.For<ITagRepository>();
    private readonly IAutoPlaylistGroupingService _grouping = Substitute.For<IAutoPlaylistGroupingService>();
    private readonly IPlaylistJobResolver _resolver = Substitute.For<IPlaylistJobResolver>();
    private readonly IUserSettingsService _settings = Substitute.For<IUserSettingsService>();
    private readonly IServiceScopeFactory _scopeFactory = Substitute.For<IServiceScopeFactory>();

    public AutoPlaylistSyncServiceTests()
    {
        _unitOfWork.Playlists.Returns(_playlists);
        _unitOfWork.Tags.Returns(_tags);
        _unitOfWork.Jobs.Returns(_jobs);
        _jobs.AddAsync(Arg.Any<Job>(), Arg.Any<CancellationToken>())
            .Returns(call => call.Arg<Job>());
        var scope = Substitute.For<IServiceScope>();
        var provider = Substitute.For<IServiceProvider>();
        provider.GetService(typeof(IUnitOfWork)).Returns(_unitOfWork);
        scope.ServiceProvider.Returns(provider);
        _scopeFactory.CreateScope().Returns(scope);
        _settings.GetBehaviorAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new BehaviorSettingsValue());
        _playlists.GetSupersededGenrePlaylistIdsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Guid>());
    }

    private AutoPlaylistSyncService CreateSut(int minTracks = 10)
    {
        _settings.GetBehaviorAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new BehaviorSettingsValue { AutoPlaylistMinTracks = minTracks });
        return new AutoPlaylistSyncService(
            _unitOfWork, _grouping, _resolver, _settings, _scopeFactory,
            NullLogger<AutoPlaylistSyncService>.Instance);
    }

    private static AutoPlaylistGroupingResult GroupingWithArtist() => new(
        [new ArtistGroup("arcane", "Arcane", [FileOne, FileTwo])],
        [],
        [],
        [],
        [],
        []);

    private void GivenResolutions(params (Guid File, Guid Job)[] resolutions)
    {
        _resolver.ResolveForOwnerAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(resolutions
                .Select(r => new PlaylistJobResolution(r.File, r.Job))
                .ToList());
    }

    private void GivenGrouping(AutoPlaylistGroupingResult grouping)
    {
        _grouping.GetGroupingAsync(Owner, Arg.Any<CancellationToken>()).Returns(grouping);
    }

    private static Playlist AutoPlaylist() => new()
    {
        Id = PlaylistId,
        Name = "Arcane",
        OwnerId = Owner,
        IsAutoGenerated = true,
        AutoGroupKind = AutoGroupKind.Artist,
        AutoArtistKey = "arcane",
    };

    [Fact]
    public async Task SyncFileAsync_creates_playlist_on_first_match_and_adds_job()
    {
        GivenGrouping(GroupingWithArtist());
        GivenResolutions((FileOne, JobOne), (FileTwo, Guid.NewGuid()));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null, Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        Playlist? created = null;
        _playlists.CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>())
            .Returns(call => created = call.Arg<Playlist>());
        _playlists.GetItemsIncludingDeletedAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistIdsForFileAsync(Owner, FileOne, Arg.Any<CancellationToken>())
            .Returns(new List<Guid>());

        var result = await CreateSut().SyncFileAsync(FileOne, Owner, TestContext.Current.CancellationToken);

        created.Should().NotBeNull();
        created!.OwnerId.Should().Be(Owner);
        created.IsAutoGenerated.Should().BeTrue();
        created.AutoGroupKind.Should().Be(AutoGroupKind.Artist);
        created.AutoArtistKey.Should().Be("arcane");
        created.Name.Should().Be("Arcane");
        await _playlists.Received(1).AddAutoItemAsync(
            created.Id, JobOne, Owner, Arg.Any<CancellationToken>());
        await _playlists.Received(1).TouchAutoPlaylistAsync(created.Id, Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(1, 2, 0, 0));
    }

    [Fact]
    public async Task SyncFileAsync_skips_create_when_nothing_resolves()
    {
        GivenGrouping(GroupingWithArtist());
        GivenResolutions();
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null, Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        _playlists.GetOwnerAutoPlaylistIdsForFileAsync(Owner, FileOne, Arg.Any<CancellationToken>())
            .Returns(new List<Guid>());

        var result = await CreateSut().SyncFileAsync(FileOne, Owner, TestContext.Current.CancellationToken);

        await _playlists.DidNotReceive().CreateAsync(
            Arg.Any<Playlist>(), Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(0, 0, 0, 0));
    }

    [Fact]
    public async Task SyncFileAsync_user_tombstone_blocks_readd()
    {
        GivenGrouping(GroupingWithArtist());
        GivenResolutions((FileOne, JobOne));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null, Arg.Any<CancellationToken>())
            .Returns(AutoPlaylist());
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>
            {
                new(ItemId, JobOne, true, true, DateTime.UtcNow),
            });
        _playlists.GetOwnerAutoPlaylistIdsForFileAsync(Owner, FileOne, Arg.Any<CancellationToken>())
            .Returns(new List<Guid>());

        var result = await CreateSut().SyncFileAsync(FileOne, Owner, TestContext.Current.CancellationToken);

        await _playlists.DidNotReceive().AddAutoItemAsync(
            Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<CancellationToken>());
        await _playlists.Received(1).TouchAutoPlaylistAsync(PlaylistId, Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(1, 0, 0, 0));
    }

    [Fact]
    public async Task SyncFileAsync_removes_file_from_grouping_it_left()
    {
        GivenGrouping(new AutoPlaylistGroupingResult([], [], [], [], [], []));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetOwnerAutoPlaylistIdsForFileAsync(Owner, FileOne, Arg.Any<CancellationToken>())
            .Returns(new List<Guid> { PlaylistId });
        _playlists.GetByIdAsync(PlaylistId, Arg.Any<CancellationToken>()).Returns(AutoPlaylist());
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>
            {
                new(ItemId, JobOne, false, false, null),
            });

        var result = await CreateSut().SyncFileAsync(FileOne, Owner, TestContext.Current.CancellationToken);

        await _playlists.Received(1).RemoveAutoItemAsync(ItemId, Owner, Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(1, 0, 0, 1));
    }

    [Fact]
    public async Task SyncFileAsync_file_matching_nothing_touches_nothing()
    {
        GivenGrouping(new AutoPlaylistGroupingResult([], [], [], [], [], []));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetOwnerAutoPlaylistIdsForFileAsync(Owner, FileOne, Arg.Any<CancellationToken>())
            .Returns(new List<Guid>());

        var result = await CreateSut().SyncFileAsync(FileOne, Owner, TestContext.Current.CancellationToken);

        await _playlists.DidNotReceive().CreateAsync(
            Arg.Any<Playlist>(), Arg.Any<CancellationToken>());
        await _playlists.DidNotReceive().TouchAutoPlaylistAsync(
            Arg.Any<Guid>(), Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(0, 0, 0, 0));
    }

    [Fact]
    public async Task SyncOwnerAsync_creates_playlist_per_kind_with_desired_jobs()
    {
        var tagId = Guid.NewGuid();
        GivenGrouping(new AutoPlaylistGroupingResult(
            [new ArtistGroup("arcane", "Arcane", [FileOne])],
            [new AlbumGroup("arcane", "lol", "Arcane", "LoL", [FileOne])],
            [new TagGroup(tagId, null, [FileOne])],
            [new GenreFallbackGroup("rock", "Rock", [FileOne])],
            [],
            []));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetAutoPlaylistAsync(
                Owner, Arg.Any<AutoGroupKind>(), Arg.Any<string?>(), Arg.Any<string?>(),
                Arg.Any<Guid?>(), Arg.Any<string?>(), Arg.Any<int?>(), Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        _playlists.CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>())
            .Returns(call => call.Arg<Playlist>());
        _playlists.GetItemsIncludingDeletedAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist>());
        _tags.GetByIdAsync(tagId, Arg.Any<CancellationToken>())
            .Returns(new Tag { Name = "Rock", Icon = "i", Color = "c", OwnerId = Owner });

        var result = await CreateSut(minTracks: 1).SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.Received(4).CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>());
        await _playlists.Received(1).CreateAsync(
            Arg.Is<Playlist>(p => p.AutoGroupKind == AutoGroupKind.Tag && p.Name == "Rock"),
            Arg.Any<CancellationToken>());
        result.PlaylistsSynced.Should().Be(4);
        result.ItemsAdded.Should().Be(4);
    }

    [Fact]
    public async Task SyncOwnerAsync_reaps_strays_from_existing_playlists()
    {
        GivenGrouping(new AutoPlaylistGroupingResult([], [], [], [], [], []));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist> { AutoPlaylist() });
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>
            {
                new(ItemId, JobOne, false, false, null),
            });

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.DidNotReceive().CreateAsync(
            Arg.Any<Playlist>(), Arg.Any<CancellationToken>());
        await _playlists.Received(1).RemoveAutoItemAsync(ItemId, Owner, Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(1, 0, 0, 1));
    }

    [Fact]
    public async Task SyncOwnerAsync_tag_bucket_below_minimum_skips_create()
    {
        var tagId = Guid.NewGuid();
        var files = new[] { FileOne, FileTwo, Guid.NewGuid() };
        GivenGrouping(new AutoPlaylistGroupingResult(
            [],
            [],
            [new TagGroup(tagId, null, files)],
            [],
            [],
            []));
        GivenResolutions(files.Select(f => (f, Guid.NewGuid())).ToArray());
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Tag, null, null, tagId, null, null, Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist>());

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.DidNotReceive().CreateAsync(
            Arg.Any<Playlist>(), Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(0, 0, 0, 0));
    }

    [Fact]
    public async Task SyncOwnerAsync_tag_bucket_at_minimum_creates()
    {
        var tagId = Guid.NewGuid();
        var files = Enumerable.Range(0, 10).Select(_ => Guid.NewGuid()).ToList();
        GivenGrouping(new AutoPlaylistGroupingResult(
            [],
            [],
            [new TagGroup(tagId, null, files)],
            [],
            [],
            []));
        GivenResolutions(files.Select(f => (f, Guid.NewGuid())).ToArray());
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Tag, null, null, tagId, null, null, Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        _playlists.CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>())
            .Returns(call => call.Arg<Playlist>());
        _playlists.GetItemsIncludingDeletedAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist>());
        _tags.GetByIdAsync(tagId, Arg.Any<CancellationToken>())
            .Returns(new Tag { Name = "Rock", Icon = "i", Color = "c", OwnerId = Owner });

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.Received(1).CreateAsync(
            Arg.Is<Playlist>(p => p.AutoGroupKind == AutoGroupKind.Tag && p.AutoTagId == tagId),
            Arg.Any<CancellationToken>());
        result.PlaylistsSynced.Should().Be(1);
        result.ItemsAdded.Should().Be(10);
    }

    [Fact]
    public async Task SyncOwnerAsync_artist_bucket_below_minimum_still_creates()
    {
        GivenGrouping(new AutoPlaylistGroupingResult(
            [new ArtistGroup("arcane", "Arcane", [FileOne])],
            [],
            [],
            [],
            [],
            []));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null, Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        _playlists.CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>())
            .Returns(call => call.Arg<Playlist>());
        _playlists.GetItemsIncludingDeletedAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist>());

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.Received(1).CreateAsync(
            Arg.Is<Playlist>(p => p.AutoGroupKind == AutoGroupKind.Artist),
            Arg.Any<CancellationToken>());
        result.PlaylistsSynced.Should().Be(1);
    }

    [Fact]
    public async Task SyncOwnerAsync_parent_genre_bucket_creates_rollup()
    {
        var parentId = Guid.NewGuid();
        GivenGrouping(new AutoPlaylistGroupingResult(
            [],
            [],
            [],
            [],
            [new ParentGenreGroup(parentId, "Rock", [FileOne, FileTwo])],
            []));
        GivenResolutions((FileOne, JobOne), (FileTwo, Guid.NewGuid()));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.ParentGenre, null, null, parentId, null, null,
                Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        _playlists.CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>())
            .Returns(call => call.Arg<Playlist>());
        _playlists.GetItemsIncludingDeletedAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist>());

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.Received(1).CreateAsync(
            Arg.Is<Playlist>(p =>
                p.AutoGroupKind == AutoGroupKind.ParentGenre
                && p.AutoTagId == parentId
                && p.Name == "Rock"),
            Arg.Any<CancellationToken>());
        result.PlaylistsSynced.Should().Be(1);
        result.ItemsAdded.Should().Be(2);
    }

    [Fact]
    public async Task SyncOwnerAsync_genre_facet_tag_creates_no_playlist()
    {
        var tagId = Guid.NewGuid();
        GivenGrouping(new AutoPlaylistGroupingResult(
            [],
            [],
            [new TagGroup(tagId, TagFacet.Genre, [FileOne])],
            [],
            [],
            []));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist>());

        var result = await CreateSut(minTracks: 1).SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.DidNotReceive().GetAutoPlaylistAsync(
            Owner, AutoGroupKind.Tag, Arg.Any<string?>(), Arg.Any<string?>(),
            Arg.Any<Guid?>(), Arg.Any<string?>(), Arg.Any<int?>(), Arg.Any<CancellationToken>());
        await _playlists.DidNotReceive().CreateAsync(
            Arg.Any<Playlist>(), Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(0, 0, 0, 0));
    }

    [Fact]
    public async Task SyncOwnerAsync_decade_bucket_creates_playlist()
    {
        GivenGrouping(new AutoPlaylistGroupingResult(
            [],
            [],
            [],
            [],
            [],
            [new DecadeGroup(2010, [FileOne])]));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Decade, null, null, null, null, 2010,
                Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        _playlists.CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>())
            .Returns(call => call.Arg<Playlist>());
        _playlists.GetItemsIncludingDeletedAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist>());

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.Received(1).CreateAsync(
            Arg.Is<Playlist>(p =>
                p.AutoGroupKind == AutoGroupKind.Decade
                && p.AutoDecade == 2010
                && p.Name == "2010s"),
            Arg.Any<CancellationToken>());
        result.PlaylistsSynced.Should().Be(1);
    }

    [Fact]
    public async Task SyncOwnerAsync_dissolves_superseded_genre_playlists()
    {
        var supersededId = Guid.NewGuid();
        GivenGrouping(new AutoPlaylistGroupingResult([], [], [], [], [], []));
        GivenResolutions();
        _playlists.GetSupersededGenrePlaylistIdsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Guid> { supersededId });
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist>());

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.Received(1).SoftDeleteAsync(supersededId, Owner, Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(0, 0, 0, 0));
    }

    [Fact]
    public async Task SyncOwnerAsync_stable_state_makes_no_item_mutations()
    {
        var jobTwo = Guid.NewGuid();
        GivenGrouping(GroupingWithArtist());
        GivenResolutions((FileOne, JobOne), (FileTwo, jobTwo));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null,
                Arg.Any<CancellationToken>())
            .Returns(AutoPlaylist());
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>
            {
                new(ItemId, JobOne, false, false, null),
                new(Guid.NewGuid(), jobTwo, false, false, null),
            });
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist> { AutoPlaylist() });

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.DidNotReceive().CreateAsync(
            Arg.Any<Playlist>(), Arg.Any<CancellationToken>());
        await _playlists.DidNotReceive().AddAutoItemAsync(
            Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<CancellationToken>());
        await _playlists.DidNotReceive().ReviveAutoItemAsync(
            Arg.Any<Guid>(), Arg.Any<CancellationToken>());
        await _playlists.DidNotReceive().RemoveAutoItemAsync(
            Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(1, 0, 0, 0));
    }

    [Fact]
    public async Task SyncOwnerAsync_tombstoned_track_stays_removed()
    {
        var jobTwo = Guid.NewGuid();
        GivenGrouping(GroupingWithArtist());
        GivenResolutions((FileOne, JobOne), (FileTwo, jobTwo));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null,
                Arg.Any<CancellationToken>())
            .Returns(AutoPlaylist());
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>
            {
                new(ItemId, JobOne, true, true, DateTime.UtcNow),
                new(Guid.NewGuid(), jobTwo, false, false, null),
            });
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist> { AutoPlaylist() });

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.DidNotReceive().AddAutoItemAsync(
            Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<Guid>(), Arg.Any<CancellationToken>());
        await _playlists.DidNotReceive().ReviveAutoItemAsync(
            Arg.Any<Guid>(), Arg.Any<CancellationToken>());
        result.Should().Be(new AutoPlaylistSyncResult(1, 0, 0, 0));
    }

    [Fact]
    public async Task SyncOwnerAsync_rename_moves_track_between_playlists()
    {
        GivenGrouping(new AutoPlaylistGroupingResult(
            [new ArtistGroup("beta", "Beta", [FileOne])],
            [],
            [],
            [],
            [],
            []));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetAutoPlaylistAsync(
                Owner, Arg.Any<AutoGroupKind>(), Arg.Any<string?>(), Arg.Any<string?>(),
                Arg.Any<Guid?>(), Arg.Any<string?>(), Arg.Any<int?>(), Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        _playlists.CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>())
            .Returns(call => call.Arg<Playlist>());
        _playlists.GetItemsIncludingDeletedAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist> { AutoPlaylist() });
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>
            {
                new(ItemId, JobOne, false, false, null),
            });

        var result = await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _playlists.Received(1).CreateAsync(
            Arg.Is<Playlist>(p =>
                p.AutoGroupKind == AutoGroupKind.Artist && p.AutoArtistKey == "beta"),
            Arg.Any<CancellationToken>());
        await _playlists.Received(1).RemoveAutoItemAsync(ItemId, Owner, Arg.Any<CancellationToken>());
        result.PlaylistsSynced.Should().Be(2);
        result.ItemsAdded.Should().Be(1);
        result.ItemsRemoved.Should().Be(1);
    }

    [Fact]
    public async Task SyncFileAsync_records_ready_run_on_success()
    {
        GivenGrouping(GroupingWithArtist());
        GivenResolutions((FileOne, JobOne), (FileTwo, Guid.NewGuid()));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null, Arg.Any<CancellationToken>())
            .Returns(AutoPlaylist());
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistIdsForFileAsync(Owner, FileOne, Arg.Any<CancellationToken>())
            .Returns(new List<Guid>());

        await CreateSut().SyncFileAsync(FileOne, Owner, TestContext.Current.CancellationToken);

        await _jobs.Received(1).AddAsync(
            Arg.Is<Job>(j =>
                j.Type == JobType.PlaylistSync
                && j.UserId == Owner
                && j.Status == JobStatus.Ready
                && j.ErrorDetail == null
                && j.StartedAt != null
                && j.CompletedAt != null),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task SyncFileAsync_records_failed_run_and_rethrows()
    {
        _grouping.GetGroupingAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(Task.FromException<AutoPlaylistGroupingResult>(
                new InvalidOperationException("boom")));

        var act = () => CreateSut().SyncFileAsync(
            FileOne, Owner, TestContext.Current.CancellationToken);

        await act.Should().ThrowAsync<InvalidOperationException>().WithMessage("boom");
        await _jobs.Received(1).AddAsync(
            Arg.Is<Job>(j =>
                j.Type == JobType.PlaylistSync
                && j.UserId == Owner
                && j.Status == JobStatus.Failed
                && j.ErrorDetail == "boom"),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task SyncOwnerAsync_records_ready_run_on_success()
    {
        GivenGrouping(GroupingWithArtist());
        GivenResolutions((FileOne, JobOne), (FileTwo, Guid.NewGuid()));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null, Arg.Any<CancellationToken>())
            .Returns(AutoPlaylist());
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistsAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(new List<Playlist> { AutoPlaylist() });

        await CreateSut().SyncOwnerAsync(Owner, TestContext.Current.CancellationToken);

        await _jobs.Received(1).AddAsync(
            Arg.Is<Job>(j =>
                j.Type == JobType.PlaylistSync
                && j.UserId == Owner
                && j.Status == JobStatus.Ready),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task SyncOwnerAsync_records_failed_run_and_rethrows()
    {
        _grouping.GetGroupingAsync(Owner, Arg.Any<CancellationToken>())
            .Returns(Task.FromException<AutoPlaylistGroupingResult>(
                new InvalidOperationException("boom")));

        var act = () => CreateSut().SyncOwnerAsync(
            Owner, TestContext.Current.CancellationToken);

        await act.Should().ThrowAsync<InvalidOperationException>().WithMessage("boom");
        await _jobs.Received(1).AddAsync(
            Arg.Is<Job>(j =>
                j.Status == JobStatus.Failed && j.ErrorDetail == "boom"),
            Arg.Any<CancellationToken>());
    }

    [Fact]
    public async Task SyncFileAsync_bounds_overlong_album_name_without_merging_keys()
    {
        var artist = new string('a', 130);
        var album = new string('b', 130);
        GivenGrouping(new AutoPlaylistGroupingResult(
            [],
            [new AlbumGroup("aaa", "bbb", artist, album, [FileOne])],
            [],
            [],
            [],
            []));
        GivenResolutions((FileOne, JobOne));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Album, "aaa", "bbb", null, null, null,
                Arg.Any<CancellationToken>())
            .Returns((Playlist?)null);
        Playlist? created = null;
        _playlists.CreateAsync(Arg.Any<Playlist>(), Arg.Any<CancellationToken>())
            .Returns(call => created = call.Arg<Playlist>());
        _playlists.GetItemsIncludingDeletedAsync(Arg.Any<Guid>(), Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistIdsForFileAsync(Owner, FileOne, Arg.Any<CancellationToken>())
            .Returns(new List<Guid>());

        await CreateSut().SyncFileAsync(FileOne, Owner, TestContext.Current.CancellationToken);

        created.Should().NotBeNull();
        created!.Name.Length.Should().BeLessThanOrEqualTo(255);
        created.AutoArtistKey.Should().Be("aaa");
        created.AutoAlbumKey.Should().Be("bbb");
    }

    [Fact]
    public async Task SyncFileAsync_telemetry_failure_does_not_fail_sync()
    {
        GivenGrouping(GroupingWithArtist());
        GivenResolutions((FileOne, JobOne), (FileTwo, Guid.NewGuid()));
        _playlists.GetAutoPlaylistAsync(
                Owner, AutoGroupKind.Artist, "arcane", null, null, null, null, Arg.Any<CancellationToken>())
            .Returns(AutoPlaylist());
        _playlists.GetItemsIncludingDeletedAsync(PlaylistId, Arg.Any<CancellationToken>())
            .Returns(new List<PlaylistItemState>());
        _playlists.GetOwnerAutoPlaylistIdsForFileAsync(Owner, FileOne, Arg.Any<CancellationToken>())
            .Returns(new List<Guid>());
        _jobs.AddAsync(Arg.Any<Job>(), Arg.Any<CancellationToken>())
            .Returns(Task.FromException<Job>(new InvalidOperationException("telemetry down")));

        var result = await CreateSut().SyncFileAsync(FileOne, Owner, TestContext.Current.CancellationToken);

        result.Should().NotBeNull();
    }
}