#!/bin/sh
set -e

echo "=== Garage Init ==="
echo ""

# ── Helpers
g() { /garage "$@"; }

# ── Wait
until g status 2>&1 | grep -q "HEALTHY NODES"; do
  sleep 2
done

mkdir -p ~/.aws
cat > ~/.aws/config << 'EOF'
[default]
s3 =
    addressing_style = path
s3api =
    addressing_style = path
EOF

echo "Garage is up"
echo ""

# ── Layout
echo "Step 1: Layout..."
NODE_ID=$(g node id | head -1 | cut -d'@' -f1 | tr -d '\r\n')
echo "  Node ID: $NODE_ID"

LAYOUT_OUTPUT=$(g layout show 2>&1)
LAYOUT_VERSION=$(echo "$LAYOUT_OUTPUT" | grep -oE "Current cluster layout version: [0-9]+" | grep -oE "[0-9]+$" || echo "0")

if echo "$LAYOUT_OUTPUT" | grep -q "No nodes currently have a role"; then
  g layout assign -z dc1 -c 10G "$NODE_ID"
  NEXT_VERSION=$((LAYOUT_VERSION + 1))
  g layout apply --version "$NEXT_VERSION"
  echo "  Layout applied (version $NEXT_VERSION)"
  sleep 3
else
  echo "  Layout already configured"
fi

# ── Buckets
echo ""
echo "Step 2: Buckets..."
for bucket in alexandria-files alexandria-previews alexandria-temp alexandria-images alexandria-streaming; do
  if g bucket list 2>/dev/null | grep -q "$bucket"; then
    echo "  Already exists: $bucket"
  else
    g bucket create "$bucket"
    echo "  Created: $bucket"
  fi
done

# Enable web endpoint for streaming bucket so nginx can proxy to port 3902
# without S3 auth. The bucket is not externally reachable — nginx enforces
# auth_request before any request reaches Garage.
echo ""
echo "Step 2b: Web endpoint..."
g bucket website --allow alexandria-streaming
echo "  Web endpoint enabled: alexandria-streaming"

# ── Keys
echo ""
echo "Step 3: Keys..."

if ! g key list | grep -q "alexandria-master-key"; then
  g key create alexandria-master-key
  echo "  Created: alexandria-master-key"
else
  echo "  Already exists: alexandria-master-key"
fi

if ! g key list | grep -q "alexandria-preview-key"; then
  g key create alexandria-preview-key
  echo "  Created: alexandria-preview-key"
else
  echo "  Already exists: alexandria-preview-key"
fi

if ! g key list | grep -q "alexandria-streaming-key"; then
  g key create alexandria-streaming-key
  echo "  Created: alexandria-streaming-key"
else
  echo "  Already exists: alexandria-streaming-key"
fi

MASTER_KEY_ID=$(g key info alexandria-master-key | grep "Key ID"     | awk '{print $NF}' | tr -d '[:space:]')
MASTER_SECRET=$(g key info --show-secret alexandria-master-key  | grep "Secret key" | awk '{print $NF}' | tr -d '[:space:]')
PREVIEW_KEY_ID=$(g key info alexandria-preview-key | grep "Key ID"     | awk '{print $NF}' | tr -d '[:space:]')
PREVIEW_SECRET=$(g key info --show-secret alexandria-preview-key | grep "Secret key" | awk '{print $NF}' | tr -d '[:space:]')
STREAMING_KEY_ID=$(g key info alexandria-streaming-key | grep "Key ID" | awk '{print $NF}' | tr -d '[:space:]')
STREAMING_SECRET=$(g key info --show-secret alexandria-streaming-key | grep "Secret key" | awk '{print $NF}' | tr -d '[:space:]')

# ── Permissions
echo ""
echo "Step 4: Permissions..."
for bucket in alexandria-files alexandria-previews alexandria-temp alexandria-images alexandria-streaming; do
  g bucket allow --read --write --owner "$bucket" --key alexandria-master-key
  echo "  Master key -> full access -> $bucket"
done

g bucket allow --read --write alexandria-previews --key alexandria-preview-key
g bucket allow --read         alexandria-files    --key alexandria-preview-key
echo "  Preview key -> read/write -> alexandria-previews"
echo "  Preview key -> read       -> alexandria-files"

g bucket allow --read         alexandria-files     --key alexandria-streaming-key
g bucket allow --read --write alexandria-streaming --key alexandria-streaming-key
echo "  Streaming key -> read       -> alexandria-files"
echo "  Streaming key -> read/write -> alexandria-streaming"

# ── CORS
echo ""
echo "Step 5: CORS..."
CORS_ORIGIN="${CORS_ORIGIN:-http://localhost:5173}"

export AWS_ACCESS_KEY_ID="$MASTER_KEY_ID"
export AWS_SECRET_ACCESS_KEY="$MASTER_SECRET"
export AWS_DEFAULT_REGION="garage"

echo "  Key ID: '${MASTER_KEY_ID}'"
echo "  Secret (first 8): '${MASTER_SECRET:0:8}'"

aws configure set default.s3.addressing_style path
sed "s|CORS_ORIGIN_PLACEHOLDER|${CORS_ORIGIN}|g" /config/cors.json > /tmp/cors.json

aws --endpoint-url http://garage:3900 \
    s3api put-bucket-cors \
    --bucket alexandria-images \
    --cors-configuration file:///tmp/cors.json

# ── Credentials
echo ""
echo "Step 7: Writing credentials..."
mkdir -p /output

cat > /output/garage-credentials.env <<EOF
# Generated by garage-init on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Copy these values into your .env file

GARAGE_S3_ACCESS_KEY=$MASTER_KEY_ID
GARAGE_S3_SECRET_KEY=$MASTER_SECRET

# Preview key (media worker)
GARAGE_PREVIEW_KEY_ID=$PREVIEW_KEY_ID
GARAGE_PREVIEW_SECRET=$PREVIEW_SECRET

# Streaming key (transpilation worker)
GARAGE_STREAMING_KEY_ID=$STREAMING_KEY_ID
GARAGE_STREAMING_SECRET=$STREAMING_SECRET
EOF

echo "  Credentials written to ./init-output/garage-credentials.env"

echo ""
echo "=== Done ==="
