using Alexandria.Data.Models;
using Alexandria.Data.Models.Enumerators;
using Alexandria.Dto.Files;
using Alexandria.Dto.Files.Streaming.Playlist;

namespace Alexandria.Common.Repositories;

/// <summary>Repository for <see cref="Playlist"/> persistence operations.</summary>
public interface IPlaylistRepository : IRepository<Playlist>
{
    /// <summary>Creates and persists a new playlist, cascading timestamps to any initial items.</summary>
    Task<Playlist> CreateAsync(Playlist entity, CancellationToken ct = default);

    /// <summary>Persists changes to an existing playlist and returns the updated instance.</summary>
    Task<Playlist> UpdateAsync(Playlist entity, CancellationToken ct = default);

    /// <summary>Returns a summary projection with a live item count. Used after mutations.</summary>
    Task<PlaylistDto?> GetSummaryAsync(Guid id, Guid userId, CancellationToken ct = default);

    /// <summary>
    /// Returns the playlist with its ordered non-deleted items projected to a detail DTO,
    /// including the representation list for each item resolved via the
    /// PlaylistItem -> TranspilationJob -> FileVersion -> File chain.
    /// </summary>
    Task<PlaylistDetailDto?> GetWithItemsAsync(Guid id, Guid userId, CancellationToken ct = default);

    /// <summary>Returns a paginated list of playlists owned by the given user.
    /// Optional origin/kind narrow the set before counting; sort orders before paging.</summary>
    Task<PaginatedResult<PlaylistDto>> GetByUserAsync(
        Guid userId,
        int page,
        int pageSize,
        bool? isAutoGenerated = null,
        AutoGroupKind? kind = null,
        PlaylistSort sort = PlaylistSort.Newest,
        CancellationToken ct = default);

    /// <summary>Soft-deletes the playlist and cascades the deletion to all its items atomically.</summary>
    Task SoftDeleteAsync(Guid playlistId, Guid userId, CancellationToken ct = default);

    /// <summary>Updates each item's Position according to the provided ordered ID sequence.</summary>
    Task ReorderItemsAsync(Guid playlistId, Guid[] orderedItemIds, CancellationToken ct = default);

    /// <summary>
    /// Appends an item at the next available position and returns the projected DTO,
    /// resolving file name, MIME type, segment prefix and representations from
    /// the TranspilationJob chain.
    /// </summary>
    Task<PlaylistItemDto> AddItemAsync(PlaylistItem item, CancellationToken ct = default);

    /// <summary>Soft-deletes a single playlist item.</summary>
    Task RemoveItemAsync(Guid playlistId, Guid itemId, Guid userId, CancellationToken ct = default);

    /// <summary>
    /// Returns a random Preview.Path sourced from the files that back the given transpilation jobs.
    /// Returns null when none of those files have a non-deleted preview.
    /// </summary>
    // Task<string?> GetRandomPreviewPathForJobsAsync(Guid[] jobIds, CancellationToken ct = default);

    /// <summary>Returns whether the given user is the owner of the playlist and it has not been deleted.</summary>
    Task<bool> IsOwnerAsync(Guid playlistId, Guid userId, CancellationToken ct = default);

    /// <summary>
    /// Finds a live auto-maintained playlist by its grouping key. Only the key columns
    /// of the given kind are matched; pass null for the rest.
    /// </summary>
    Task<Playlist?> GetAutoPlaylistAsync(
        Guid ownerId,
        AutoGroupKind kind,
        string? artistKey,
        string? albumKey,
        Guid? tagId,
        string? genreKey,
        int? decade,
        CancellationToken ct = default);

    /// <summary>
    /// Every item of a playlist including soft-deleted rows, as reconciler state.
    /// Ordered by id for deterministic diffs.
    /// </summary>
    Task<IReadOnlyList<PlaylistItemState>> GetItemsIncludingDeletedAsync(
        Guid playlistId, CancellationToken ct = default);

    /// <summary>
    /// Ids of the owner's live auto playlists that hold a live item bound to any
    /// transcode job of the given file's versions. Finds playlists the file left
    /// (rename, tag removal) so they can drop it.
    /// </summary>
    Task<IReadOnlyList<Guid>> GetOwnerAutoPlaylistIdsForFileAsync(
        Guid ownerId, Guid fileId, CancellationToken ct = default);

    /// <summary>
    /// Plain reconciler insert at the next position. Never touches user tombstones;
    /// the diff decides beforehand whether this insert is allowed.
    /// </summary>
    Task<PlaylistItem> AddAutoItemAsync(
        Guid playlistId, Guid transpilationJobId, Guid ownerId, CancellationToken ct = default);

    /// <summary>Clears the soft-delete of a system-removed row (flag stays false).</summary>
    Task ReviveAutoItemAsync(Guid itemId, CancellationToken ct = default);

    /// <summary>System soft-delete: sets DeletedAt, leaves RemovedByUser false.</summary>
    Task RemoveAutoItemAsync(Guid itemId, Guid ownerId, CancellationToken ct = default);

    /// <summary>Stamps the playlist's LastSyncedAt with the current time.</summary>
    Task TouchAutoPlaylistAsync(Guid playlistId, CancellationToken ct = default);

    /// <summary>
    /// Ids of live auto Tag-kind playlists whose tag is a genre-facet child. Parent
    /// rollups replace these (D17); the worker dissolves them so they do not linger
    /// under the creation-hysteresis rule.
    /// </summary>
    Task<IReadOnlyList<Guid>> GetSupersededGenrePlaylistIdsAsync(
        Guid ownerId, CancellationToken ct = default);

    /// <summary>Distinct owners of live files. Sweep entry: covers owners whose files
    /// predate every playlist event, so existing libraries get playlists too.</summary>
    Task<IReadOnlyList<Guid>> GetSyncOwnerIdsAsync(CancellationToken ct = default);

    /// <summary>Live auto-maintained playlists of one owner, with grouping columns.</summary>
    Task<IReadOnlyList<Playlist>> GetOwnerAutoPlaylistsAsync(Guid ownerId, CancellationToken ct = default);
}