import { describe, expect, it } from "vitest";

import { AutoGroupKind } from "@/enums/auto-group-kind";
import { PlaylistSort } from "@/enums/playlist-sort";
import {
  autoGroupKindLabel,
  DEFAULT_BROWSE_STATE,
  parsePlaylistBrowseQuery,
  playlistBadgeLabel,
  playlistBrowseQuery,
} from "@/utils/playlist-display.utils";

const item = (
  overrides: Partial<{
    isAutoGenerated: boolean;
    autoGroupKind: AutoGroupKind | null;
  }> = {},
) => ({
  isAutoGenerated: false,
  autoGroupKind: null as AutoGroupKind | null,
  ...overrides,
});

describe("autoGroupKindLabel", () => {
  it("labels every known kind", () => {
    expect(autoGroupKindLabel(AutoGroupKind.Artist)).toBe("Artist");
    expect(autoGroupKindLabel(AutoGroupKind.Album)).toBe("Album");
    expect(autoGroupKindLabel(AutoGroupKind.Tag)).toBe("Tag");
    expect(autoGroupKindLabel(AutoGroupKind.Genre)).toBe("Genre");
    expect(autoGroupKindLabel(AutoGroupKind.ParentGenre)).toBe("Genre");
    expect(autoGroupKindLabel(AutoGroupKind.Decade)).toBe("Decade");
  });

  it("returns null for missing kinds", () => {
    expect(autoGroupKindLabel(null)).toBeNull();
    expect(autoGroupKindLabel(undefined)).toBeNull();
  });
});

describe("playlistBadgeLabel", () => {
  it("returns null for manual playlists", () => {
    expect(playlistBadgeLabel(item())).toBeNull();
  });

  it("combines origin and kind for auto playlists", () => {
    expect(
      playlistBadgeLabel(item({ isAutoGenerated: true, autoGroupKind: AutoGroupKind.Decade })),
    ).toBe("Auto · Decade");
  });

  it("falls back to origin only when the kind is missing", () => {
    expect(playlistBadgeLabel(item({ isAutoGenerated: true }))).toBe("Auto");
  });
});

describe("parsePlaylistBrowseQuery", () => {
  it("returns defaults for an empty query", () => {
    expect(parsePlaylistBrowseQuery({})).toEqual(DEFAULT_BROWSE_STATE);
  });

  it("parses a full valid query", () => {
    expect(parsePlaylistBrowseQuery({ page: "3", origin: "auto", kind: "5", sort: "1" })).toEqual({
      page: 3,
      origin: "auto",
      kind: AutoGroupKind.Decade,
      sort: PlaylistSort.Name,
    });
  });

  it("falls back per field on garbage", () => {
    expect(parsePlaylistBrowseQuery({ page: "0", origin: "junk", kind: "99", sort: "x" })).toEqual(
      DEFAULT_BROWSE_STATE,
    );
  });

  it("reads the first value of repeated params", () => {
    expect(parsePlaylistBrowseQuery({ page: ["2", "5"] })).toMatchObject({ page: 2 });
  });
});

describe("playlistBrowseQuery", () => {
  it("omits every default", () => {
    expect(playlistBrowseQuery(DEFAULT_BROWSE_STATE)).toEqual({});
  });

  it("serializes a full state and round-trips", () => {
    const state = {
      page: 2,
      origin: "auto" as const,
      kind: AutoGroupKind.Tag,
      sort: PlaylistSort.TrackCount,
    };
    const query = playlistBrowseQuery(state);
    expect(query).toEqual({ page: "2", origin: "auto", kind: "2", sort: "2" });
    expect(parsePlaylistBrowseQuery(query)).toEqual(state);
  });
});
