<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Alexandria.Common\Alexandria.Common.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Threading.RateLimiting"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="Alexandria.Tests.Unit"/>
        <EmbeddedResource Include="./Wrapped/Data/duration-dataset.json" Link="Resources/duration-dataset.json"
                          LogicalName="Alexandria.Wrapped.DurationDataset.json"/>
    </ItemGroup>

</Project>
