using Alexandria.Common;
using Alexandria.Common.Services;
using Alexandria.Common.Settings.Values;
using Alexandria.Data.Models;
using Alexandria.Data.Models.Enumerators;
using Alexandria.Dto.Files.Streaming.Playlist;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Alexandria.Services.Streaming;

public sealed partial class AutoPlaylistSyncService(
    IUnitOfWork unitOfWork,
    IAutoPlaylistGroupingService groupingService,
    IPlaylistJobResolver jobResolver,
    IUserSettingsService settingsService,
    IServiceScopeFactory scopeFactory,
    ILogger<AutoPlaylistSyncService> logger) : IAutoPlaylistSyncService
{
    public async Task<AutoPlaylistSyncResult> SyncFileAsync(
        Guid fileId, Guid ownerId, CancellationToken ct = default)
    {
        var startedAt = DateTime.UtcNow;
        try
        {
            var result = await SyncFileCoreAsync(fileId, ownerId, ct);
            await RecordRunAsync(ownerId, startedAt, result, null, ct);
            return result;
        }
        catch (Exception ex)
        {
            await RecordRunAsync(ownerId, startedAt, null, ex, ct);
            throw;
        }
    }

    private async Task<AutoPlaylistSyncResult> SyncFileCoreAsync(
        Guid fileId, Guid ownerId, CancellationToken ct)
    {
        var grouping = await groupingService.GetGroupingAsync(ownerId, ct);
        var jobByFile = await ResolveJobsAsync(ownerId, ct);
        var minTracks = await ResolveMinTracksAsync(ownerId, ct);

        await DissolveSupersededAsync(ownerId, ct);

        var playlists = new Dictionary<Guid, Playlist>();

        foreach (var group in AllGroups(grouping).Where(g => g.FileIds.Contains(fileId)))
        {
            var playlist = await EnsurePlaylistAsync(ownerId, group, jobByFile, minTracks, ct);
            if (playlist is not null)
                playlists[playlist.Id] = playlist;
        }

        var reverseIds = await unitOfWork.Playlists
            .GetOwnerAutoPlaylistIdsForFileAsync(ownerId, fileId, ct);

        foreach (var playlistId in reverseIds)
        {
            if (playlists.ContainsKey(playlistId))
                continue;

            var playlist = await unitOfWork.Playlists.GetByIdAsync(playlistId, ct);
            if (playlist is not null && playlist.IsAutoGenerated)
                playlists[playlist.Id] = playlist;
        }

        var result = await SyncPlaylistsAsync(playlists.Values, grouping, jobByFile, ownerId, ct);

        LogFileSynced(logger, fileId, result.PlaylistsSynced, result.ItemsAdded,
            result.ItemsRevived, result.ItemsRemoved);

        return result;
    }

    public async Task<AutoPlaylistSyncResult> SyncOwnerAsync(
        Guid ownerId, CancellationToken ct = default)
    {
        var startedAt = DateTime.UtcNow;
        try
        {
            var result = await SyncOwnerCoreAsync(ownerId, ct);
            await RecordRunAsync(ownerId, startedAt, result, null, ct);
            return result;
        }
        catch (Exception ex)
        {
            await RecordRunAsync(ownerId, startedAt, null, ex, ct);
            throw;
        }
    }

    private async Task<AutoPlaylistSyncResult> SyncOwnerCoreAsync(
        Guid ownerId, CancellationToken ct)
    {
        var grouping = await groupingService.GetGroupingAsync(ownerId, ct);
        var jobByFile = await ResolveJobsAsync(ownerId, ct);
        var minTracks = await ResolveMinTracksAsync(ownerId, ct);

        await DissolveSupersededAsync(ownerId, ct);

        var playlists = new Dictionary<Guid, Playlist>();

        foreach (var group in AllGroups(grouping))
        {
            var playlist = await EnsurePlaylistAsync(ownerId, group, jobByFile, minTracks, ct);
            if (playlist is not null)
                playlists[playlist.Id] = playlist;
        }

        var existing = await unitOfWork.Playlists.GetOwnerAutoPlaylistsAsync(ownerId, ct);
        foreach (var playlist in existing)
        {
            if (!playlists.ContainsKey(playlist.Id))
                playlists[playlist.Id] = playlist;
        }

        var result = await SyncPlaylistsAsync(playlists.Values, grouping, jobByFile, ownerId, ct);

        LogOwnerSynced(logger, ownerId, result.PlaylistsSynced, result.ItemsAdded,
            result.ItemsRevived, result.ItemsRemoved);

        return result;
    }

    private async Task DissolveSupersededAsync(Guid ownerId, CancellationToken ct)
    {
        var ids = await unitOfWork.Playlists.GetSupersededGenrePlaylistIdsAsync(ownerId, ct);
        foreach (var playlistId in ids)
            await unitOfWork.Playlists.SoftDeleteAsync(playlistId, ownerId, ct);

        if (ids.Count > 0)
            LogDissolvedSuperseded(logger, ownerId, ids.Count);
    }

    private async Task<Dictionary<Guid, Guid>> ResolveJobsAsync(Guid ownerId, CancellationToken ct)
    {
        return (await jobResolver.ResolveForOwnerAsync(ownerId, ct))
            .ToDictionary(r => r.FileId, r => r.TranspilationJobId);
    }

    // One completed Job row per run, recorded on a fresh scope so a failed
    // operation cannot poison the telemetry save. Telemetry errors are logged,
    // never thrown; failures are rethrown to preserve worker requeue behavior.
    private async Task RecordRunAsync(
        Guid ownerId, DateTime startedAt, AutoPlaylistSyncResult? result,
        Exception? error, CancellationToken ct)
    {
        try
        {
            using var scope = scopeFactory.CreateScope();
            var jobs = scope.ServiceProvider.GetRequiredService<IUnitOfWork>().Jobs;
            await jobs.AddAsync(new Job
            {
                Id = Guid.NewGuid(),
                Type = JobType.PlaylistSync,
                UserId = ownerId,
                Status = error is null ? JobStatus.Ready : JobStatus.Failed,
                ErrorDetail = error?.Message,
                StartedAt = startedAt,
                CompletedAt = DateTime.UtcNow,
            }, ct);
        }
        catch (Exception telemetryError)
        {
            LogTelemetryFailed(logger, ownerId, telemetryError);
        }
    }

    private async Task<int> ResolveMinTracksAsync(Guid ownerId, CancellationToken ct)
    {
        var behavior = await settingsService.GetBehaviorAsync(ownerId, ct);
        return Math.Clamp(
            behavior.AutoPlaylistMinTracks,
            BehaviorSettingsValue.MinAutoPlaylistTracks,
            BehaviorSettingsValue.MaxAutoPlaylistTracks);
    }

    private async Task<Playlist?> EnsurePlaylistAsync(
        Guid ownerId,
        GroupRef group,
        IReadOnlyDictionary<Guid, Guid> jobByFile,
        int minTracks,
        CancellationToken ct)
    {
        var playlist = await unitOfWork.Playlists.GetAutoPlaylistAsync(
            ownerId, group.Kind, group.ArtistKey, group.AlbumKey,
            group.TagId, group.GenreKey, group.Decade, ct);

        if (playlist is not null)
            return playlist;

        var desired = DesiredJobs(group.FileIds, jobByFile);
        if (desired.Count == 0)
            return null;

        if (IsGatedKind(group.Kind) && desired.Count < minTracks)
            return null;

        return await unitOfWork.Playlists.CreateAsync(new Playlist
        {
            Id = Guid.NewGuid(),
            Name = BoundName(await DisplayNameAsync(group, ct)),
            OwnerId = ownerId,
            IsAutoGenerated = true,
            AutoGroupKind = group.Kind,
            AutoArtistKey = group.ArtistKey,
            AutoAlbumKey = group.AlbumKey,
            AutoTagId = group.TagId,
            AutoGenreKey = group.GenreKey,
            AutoDecade = group.Decade,
            UpdatedBy = ownerId,
        }, ct);
    }

    private async Task<AutoPlaylistSyncResult> SyncPlaylistsAsync(
        IEnumerable<Playlist> playlists,
        AutoPlaylistGroupingResult grouping,
        IReadOnlyDictionary<Guid, Guid> jobByFile,
        Guid ownerId,
        CancellationToken ct)
    {
        var synced = 0;
        var added = 0;
        var revived = 0;
        var removed = 0;

        foreach (var playlist in playlists)
        {
            var members = BucketMembers(grouping, playlist);
            var desired = DesiredJobs(members, jobByFile);
            var items = await unitOfWork.Playlists.GetItemsIncludingDeletedAsync(playlist.Id, ct);
            var diff = PlaylistReconciler.ComputeDiff(desired, items, Invert(jobByFile));

            foreach (var jobId in diff.AddJobIds)
                await unitOfWork.Playlists.AddAutoItemAsync(playlist.Id, jobId, ownerId, ct);

            foreach (var itemId in diff.ReviveItemIds)
                await unitOfWork.Playlists.ReviveAutoItemAsync(itemId, ct);

            foreach (var itemId in diff.RemoveItemIds)
                await unitOfWork.Playlists.RemoveAutoItemAsync(itemId, ownerId, ct);

            await unitOfWork.Playlists.TouchAutoPlaylistAsync(playlist.Id, ct);

            synced++;
            added += diff.AddJobIds.Count;
            revived += diff.ReviveItemIds.Count;
            removed += diff.RemoveItemIds.Count;
        }

        return new AutoPlaylistSyncResult(synced, added, revived, removed);
    }

    private static IReadOnlyDictionary<Guid, Guid> Invert(IReadOnlyDictionary<Guid, Guid> jobByFile)
    {
        var inverted = new Dictionary<Guid, Guid>();
        foreach (var (fileId, jobId) in jobByFile)
        {
            if (!inverted.ContainsKey(jobId))
                inverted[jobId] = fileId;
        }

        return inverted;
    }

    private sealed record GroupRef(
        AutoGroupKind Kind,
        string? ArtistKey,
        string? AlbumKey,
        Guid? TagId,
        string? GenreKey,
        int? Decade,
        string Display,
        IReadOnlyList<Guid> FileIds);

    private static IEnumerable<GroupRef> AllGroups(AutoPlaylistGroupingResult grouping)
    {
        foreach (var group in grouping.Artists)
            yield return new GroupRef(
                AutoGroupKind.Artist, group.Key, null, null, null, null,
                group.DisplayName, group.FileIds);

        foreach (var group in grouping.Albums)
            yield return new GroupRef(
                AutoGroupKind.Album, group.ArtistKey, group.AlbumKey, null, null, null,
                $"{group.DisplayArtist} - {group.DisplayAlbum}", group.FileIds);

        // Genre-facet tags roll up into their parent (D17); mood, user, and
        // unfaceted tags keep per-tag playlists.
        foreach (var group in grouping.Tags)
        {
            if (group.Facet == TagFacet.Genre)
                continue;
            yield return new GroupRef(
                AutoGroupKind.Tag, null, null, group.TagId, null, null,
                string.Empty, group.FileIds);
        }

        foreach (var group in grouping.GenreFallback)
            yield return new GroupRef(
                AutoGroupKind.Genre, null, null, null, group.Key, null,
                group.DisplayName, group.FileIds);

        foreach (var group in grouping.ParentGenres)
            yield return new GroupRef(
                AutoGroupKind.ParentGenre, null, null, group.ParentTagId, null, null,
                group.DisplayName, group.FileIds);

        foreach (var group in grouping.Decades)
            yield return new GroupRef(
                AutoGroupKind.Decade, null, null, null, null, group.Decade,
                $"{group.Decade}s", group.FileIds);
    }

    private static IReadOnlyList<Guid> BucketMembers(
        AutoPlaylistGroupingResult grouping, Playlist playlist)
    {
        if (playlist.AutoGroupKind == AutoGroupKind.Artist && playlist.AutoArtistKey is not null)
        {
            var match = grouping.Artists.FirstOrDefault(g => g.Key == playlist.AutoArtistKey);
            if (match is not null)
                return match.FileIds;
            return [];
        }

        if (playlist.AutoGroupKind == AutoGroupKind.Album
            && playlist.AutoArtistKey is not null
            && playlist.AutoAlbumKey is not null)
        {
            var match = grouping.Albums.FirstOrDefault(g =>
                g.ArtistKey == playlist.AutoArtistKey && g.AlbumKey == playlist.AutoAlbumKey);
            if (match is not null)
                return match.FileIds;
            return [];
        }

        if (playlist.AutoGroupKind == AutoGroupKind.Tag && playlist.AutoTagId.HasValue)
        {
            var match = grouping.Tags.FirstOrDefault(g => g.TagId == playlist.AutoTagId.Value);
            if (match is not null)
                return match.FileIds;
            return [];
        }

        if (playlist.AutoGroupKind == AutoGroupKind.Genre && playlist.AutoGenreKey is not null)
        {
            var match = grouping.GenreFallback.FirstOrDefault(g => g.Key == playlist.AutoGenreKey);
            if (match is not null)
                return match.FileIds;
            return [];
        }

        if (playlist.AutoGroupKind == AutoGroupKind.ParentGenre && playlist.AutoTagId.HasValue)
        {
            var match = grouping.ParentGenres.FirstOrDefault(g => g.ParentTagId == playlist.AutoTagId.Value);
            if (match is not null)
                return match.FileIds;
            return [];
        }

        if (playlist.AutoGroupKind == AutoGroupKind.Decade && playlist.AutoDecade.HasValue)
        {
            var match = grouping.Decades.FirstOrDefault(g => g.Decade == playlist.AutoDecade.Value);
            if (match is not null)
                return match.FileIds;
            return [];
        }

        return [];
    }

    /// <summary>
    /// Vocabulary-driven kinds (tag, genre fallback) explode into singletons without
    /// a minimum size; bounded kinds (artist, album) always materialize.
    /// </summary>
    private static bool IsGatedKind(AutoGroupKind kind)
    {
        if (kind == AutoGroupKind.Tag)
            return true;
        if (kind == AutoGroupKind.Genre)
            return true;
        return false;
    }

    private static HashSet<Guid> DesiredJobs(IEnumerable<Guid> members, IReadOnlyDictionary<Guid, Guid> jobByFile)
    {
        var desired = new HashSet<Guid>();

        foreach (var fileId in members)
        {
            if (jobByFile.TryGetValue(fileId, out var jobId))
                desired.Add(jobId);
        }

        return desired;
    }

    private async Task<string> DisplayNameAsync(GroupRef group, CancellationToken ct)
    {
        if (group.Kind == AutoGroupKind.Tag && group.TagId.HasValue)
        {
            var tag = await unitOfWork.Tags.GetByIdAsync(group.TagId.Value, ct);
            if (!string.IsNullOrWhiteSpace(tag?.Name))
                return tag!.Name;
            return "Tag";
        }

        if (group.Kind == AutoGroupKind.ParentGenre && group.TagId.HasValue)
        {
            if (!string.IsNullOrWhiteSpace(group.Display))
                return group.Display;
            var parent = await unitOfWork.Tags.GetByIdAsync(group.TagId.Value, ct);
            if (!string.IsNullOrWhiteSpace(parent?.Name))
                return parent!.Name;
            return "Genre";
        }

        return group.Display;
    }

    // Display names share a 255-char column; grouping keys stay full so an
    // overlong label shrinks instead of merging groups.
    private static string BoundName(string display)
    {
        return display.Length <= ValidationConstants.StringLengths.MediumString
            ? display
            : display[..ValidationConstants.StringLengths.MediumString];
    }
}