using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Alexandria.Data.Migrations
{
    /// <inheritdoc />
    public partial class FixPlayIndexlistNotValuingDeletedAtWhenRegenerating : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey_AutoAlbumKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoDecade",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoGenreKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoTagId",
                table: "Playlists");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoArtistKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 0 AND \"DeletedAt\" IS NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey_AutoAlbumKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoArtistKey", "AutoAlbumKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 1 AND \"DeletedAt\" IS NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoDecade",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoDecade" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 5 AND \"DeletedAt\" IS NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoGenreKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoGenreKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 3 AND \"DeletedAt\" IS NULL");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoGroupKind_AutoTagId",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoGroupKind", "AutoTagId" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" IN (2, 4) AND \"DeletedAt\" IS NULL");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey_AutoAlbumKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoDecade",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoGenreKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoGroupKind_AutoTagId",
                table: "Playlists");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoArtistKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 0");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey_AutoAlbumKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoArtistKey", "AutoAlbumKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 1");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoDecade",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoDecade" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 5");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoGenreKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoGenreKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 3");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoTagId",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoTagId" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 4");
        }
    }
}
