using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Alexandria.Data.Migrations
{
    /// <inheritdoc />
    public partial class AutoPlaylists : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "AutoAlbumKey",
                table: "Playlists",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AutoArtistKey",
                table: "Playlists",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "AutoGenreKey",
                table: "Playlists",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AutoGroupKind",
                table: "Playlists",
                type: "integer",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "AutoTagId",
                table: "Playlists",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "Playlists",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "LastSyncedAt",
                table: "Playlists",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "RemovedByUser",
                table: "PlaylistItems",
                type: "boolean",
                nullable: false,
                defaultValue: false);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "AutoAlbumKey",
                table: "Playlists");

            migrationBuilder.DropColumn(
                name: "AutoArtistKey",
                table: "Playlists");

            migrationBuilder.DropColumn(
                name: "AutoGenreKey",
                table: "Playlists");

            migrationBuilder.DropColumn(
                name: "AutoGroupKind",
                table: "Playlists");

            migrationBuilder.DropColumn(
                name: "AutoTagId",
                table: "Playlists");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "Playlists");

            migrationBuilder.DropColumn(
                name: "LastSyncedAt",
                table: "Playlists");

            migrationBuilder.DropColumn(
                name: "RemovedByUser",
                table: "PlaylistItems");
        }
    }
}
