using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Alexandria.Data.Migrations
{
    /// <inheritdoc />
    public partial class AutoPlaylistKinds : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoTagId",
                table: "Playlists");

            migrationBuilder.AddColumn<int>(
                name: "AutoDecade",
                table: "Playlists",
                type: "integer",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoDecade",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoDecade" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 5");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoTagId",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoTagId" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 4");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoDecade",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoTagId",
                table: "Playlists");

            migrationBuilder.DropColumn(
                name: "AutoDecade",
                table: "Playlists");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoTagId",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoTagId" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 2");
        }
    }
}
