using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Alexandria.Data.Migrations
{
    /// <inheritdoc />
    public partial class AutoPlaylistConstraints : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PlaylistItems_TranspilationJobs_TranspilationJobId",
                table: "PlaylistItems");

            migrationBuilder.DropForeignKey(
                name: "FK_Playlists_AspNetUsers_OwnerId",
                table: "Playlists");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Playlists",
                type: "varchar(255)",
                maxLength: 255,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<bool>(
                name: "IsAutoGenerated",
                table: "Playlists",
                type: "boolean",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "boolean");

            migrationBuilder.AlterColumn<bool>(
                name: "HasCover",
                table: "Playlists",
                type: "boolean",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "boolean");

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                table: "Playlists",
                type: "varchar(1000)",
                maxLength: 1000,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AutoGenreKey",
                table: "Playlists",
                type: "varchar(255)",
                maxLength: 255,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AutoArtistKey",
                table: "Playlists",
                type: "varchar(255)",
                maxLength: 255,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AutoAlbumKey",
                table: "Playlists",
                type: "varchar(255)",
                maxLength: 255,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AmbientTheme",
                table: "Playlists",
                type: "varchar(50)",
                maxLength: 50,
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            migrationBuilder.AlterColumn<bool>(
                name: "RemovedByUser",
                table: "PlaylistItems",
                type: "boolean",
                nullable: false,
                defaultValue: false,
                oldClrType: typeof(bool),
                oldType: "boolean");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_CreatedAt",
                table: "Playlists",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoArtistKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 0");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey_AutoAlbumKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoArtistKey", "AutoAlbumKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 1");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoGenreKey",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoGenreKey" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 3");

            migrationBuilder.CreateIndex(
                name: "IX_Playlists_OwnerId_AutoTagId",
                table: "Playlists",
                columns: new[] { "OwnerId", "AutoTagId" },
                unique: true,
                filter: "\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = 2");

            migrationBuilder.CreateIndex(
                name: "IX_PlaylistItems_CreatedAt",
                table: "PlaylistItems",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_PlaylistItems_PlaylistId_Position",
                table: "PlaylistItems",
                columns: new[] { "PlaylistId", "Position" });

            migrationBuilder.AddForeignKey(
                name: "FK_PlaylistItems_TranspilationJobs_TranspilationJobId",
                table: "PlaylistItems",
                column: "TranspilationJobId",
                principalTable: "TranspilationJobs",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Playlists_AspNetUsers_OwnerId",
                table: "Playlists",
                column: "OwnerId",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_PlaylistItems_TranspilationJobs_TranspilationJobId",
                table: "PlaylistItems");

            migrationBuilder.DropForeignKey(
                name: "FK_Playlists_AspNetUsers_OwnerId",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_CreatedAt",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoArtistKey_AutoAlbumKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoGenreKey",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_Playlists_OwnerId_AutoTagId",
                table: "Playlists");

            migrationBuilder.DropIndex(
                name: "IX_PlaylistItems_CreatedAt",
                table: "PlaylistItems");

            migrationBuilder.DropIndex(
                name: "IX_PlaylistItems_PlaylistId_Position",
                table: "PlaylistItems");

            migrationBuilder.AlterColumn<string>(
                name: "Name",
                table: "Playlists",
                type: "text",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "varchar(255)",
                oldMaxLength: 255);

            migrationBuilder.AlterColumn<bool>(
                name: "IsAutoGenerated",
                table: "Playlists",
                type: "boolean",
                nullable: false,
                oldClrType: typeof(bool),
                oldType: "boolean",
                oldDefaultValue: false);

            migrationBuilder.AlterColumn<bool>(
                name: "HasCover",
                table: "Playlists",
                type: "boolean",
                nullable: false,
                oldClrType: typeof(bool),
                oldType: "boolean",
                oldDefaultValue: false);

            migrationBuilder.AlterColumn<string>(
                name: "Description",
                table: "Playlists",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(1000)",
                oldMaxLength: 1000,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AutoGenreKey",
                table: "Playlists",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(255)",
                oldMaxLength: 255,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AutoArtistKey",
                table: "Playlists",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(255)",
                oldMaxLength: 255,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AutoAlbumKey",
                table: "Playlists",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(255)",
                oldMaxLength: 255,
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "AmbientTheme",
                table: "Playlists",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "varchar(50)",
                oldMaxLength: 50,
                oldNullable: true);

            migrationBuilder.AlterColumn<bool>(
                name: "RemovedByUser",
                table: "PlaylistItems",
                type: "boolean",
                nullable: false,
                oldClrType: typeof(bool),
                oldType: "boolean",
                oldDefaultValue: false);

            migrationBuilder.AddForeignKey(
                name: "FK_PlaylistItems_TranspilationJobs_TranspilationJobId",
                table: "PlaylistItems",
                column: "TranspilationJobId",
                principalTable: "TranspilationJobs",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_Playlists_AspNetUsers_OwnerId",
                table: "Playlists",
                column: "OwnerId",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
