using AwesomeAssertions;
using Builder.Models;
using Builder.Services;

namespace Builder.Tests.Services;

public class GarageCredentialsFileParserTests
{
    private const string ValidFileContent = """
        # Generated by garage-init on 2026-08-25T00:00:00Z
        # Copy these values into your .env file

        GARAGE_S3_ACCESS_KEY=GK_master_id
        GARAGE_S3_SECRET_KEY=master_secret

        # Preview key (media worker)
        GARAGE_PREVIEW_KEY_ID=GK_preview_id
        GARAGE_PREVIEW_SECRET=preview_secret

        # Streaming key (transpilation worker)
        GARAGE_STREAMING_KEY_ID=GK_streaming_id
        GARAGE_STREAMING_SECRET=streaming_secret
        """;

    [Fact]
    public void Parse_validContent_returnsCompleteCredentialSet()
    {
        var credentials = GarageCredentialsFileParser.Parse(ValidFileContent);

        credentials.Should().NotBeNull();
        credentials!.AccessKey.Should().Be("GK_master_id");
        credentials.AccessSecret.Should().Be("master_secret");
        credentials.PreviewKeyId.Should().Be("GK_preview_id");
        credentials.PreviewSecret.Should().Be("preview_secret");
        credentials.StreamingKeyId.Should().Be("GK_streaming_id");
        credentials.StreamingSecret.Should().Be("streaming_secret");
        credentials.IsComplete.Should().BeTrue();
    }

    [Fact]
    public void Parse_crlfLineEndings_isTolerated()
    {
        var content = ValidFileContent.Replace("\n", "\r\n");

        var credentials = GarageCredentialsFileParser.Parse(content);

        credentials.Should().NotBeNull();
    }

    [Fact]
    public void Parse_partialFile_returnsNullInsteadOfThrowing()
    {
        var content = "GARAGE_S3_ACCESS_KEY=GK_master_id\nGARAGE_S3_SECRET_KEY=\n";

        var credentials = GarageCredentialsFileParser.Parse(content);

        credentials.Should().BeNull();
    }

    [Fact]
    public void Parse_emptyOrWhitespaceContent_returnsNull()
    {
        GarageCredentialsFileParser.Parse("").Should().BeNull();
        GarageCredentialsFileParser.Parse("   \n\n").Should().BeNull();
    }

    [Fact]
    public void Parse_garbageLine_throwsFormatException()
    {
        var act = () => GarageCredentialsFileParser.Parse("this is not an env file");

        act.Should().Throw<FormatException>();
    }

    [Fact]
    public void ToEnvValues_mapsMasterPreviewStreamingOntoConsumerVariableNames()
    {
        var credentials = GarageCredentialsFileParser.Parse(ValidFileContent)!;

        var values = GarageCredentialsFileParser.ToEnvValues(credentials);

        values["GARAGE_S3_ACCESS_KEY"].Should().Be("GK_master_id");
        values["GARAGE_S3_SECRET_KEY"].Should().Be("master_secret");
        values["GARAGE_S3_WORKER_ACCESS_KEY"].Should().Be("GK_preview_id");
        values["GARAGE_S3_WORKER_SECRET_KEY"].Should().Be("preview_secret");
        values["GARAGE_S3_TRANSPILATION_WORKER_ACCESS_KEY"].Should().Be("GK_streaming_id");
        values["GARAGE_S3_TRANSPILATION_WORKER_SECRET_KEY"].Should().Be("streaming_secret");
    }
}
