import { defineQueryOptions } from "@pinia/colada";

import type { AutoGroupKind } from "@/enums/auto-group-kind";
import type { PlaylistSort } from "@/enums/playlist-sort";

import { playlistApi } from "@/api/playlist";

export const PLAYLIST_QUERY_KEYS = {
  root: ["playlists"] as const,
  // oxlint-disable-next-line max-params
  list: (
    page: number,
    pageSize: number,
    isAutoGenerated?: boolean,
    autoGroupKind?: AutoGroupKind | null,
    sort?: PlaylistSort,
  ) => [
    ...PLAYLIST_QUERY_KEYS.root,
    "list",
    page,
    pageSize,
    isAutoGenerated ?? null,
    autoGroupKind ?? null,
    sort ?? null,
  ],
  detail: (id: string) => [...PLAYLIST_QUERY_KEYS.root, "detail", id],
};

export interface GetPlaylistsQuery {
  page: number;
  pageSize: number;
  isAutoGenerated?: boolean;
  autoGroupKind?: AutoGroupKind | null;
  sort?: PlaylistSort;
}

export const getPlaylists = defineQueryOptions((query: GetPlaylistsQuery) => ({
  key: PLAYLIST_QUERY_KEYS.list(
    query.page,
    query.pageSize,
    query.isAutoGenerated,
    query.autoGroupKind,
    query.sort,
  ),
  placeholderData: (prev) => prev,
  query: () =>
    playlistApi.getAll(query.page, query.pageSize, {
      isAutoGenerated: query.isAutoGenerated,
      autoGroupKind: query.autoGroupKind,
      sort: query.sort,
    }),
}));

export const getPlaylistById = defineQueryOptions((id: string) => ({
  key: PLAYLIST_QUERY_KEYS.detail(id),
  query: () => playlistApi.getById(id),
  staleTime: 30_000,
}));
