using Alexandria.Data.Models;
using Alexandria.Data.Models.Enumerators;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Alexandria.Data.Configurations;

public class PlaylistConfiguration : IEntityTypeConfiguration<Playlist>
{
    public void Configure(EntityTypeBuilder<Playlist> builder)
    {
        builder.HasKey(e => e.Id);

        builder.Property(e => e.Name)
            .HasMaxLength(ValidationConstants.StringLengths.MediumString)
            .HasColumnType($"varchar({ValidationConstants.StringLengths.MediumString})")
            .IsRequired();

        builder.Property(e => e.Description)
            .HasMaxLength(ValidationConstants.StringLengths.LongString)
            .HasColumnType($"varchar({ValidationConstants.StringLengths.LongString})")
            .IsRequired(false);

        builder.Property(e => e.HasCover)
            .HasDefaultValue(false)
            .IsRequired();

        builder.Property(e => e.AmbientTheme)
            .HasMaxLength(ValidationConstants.StringLengths.ShortString)
            .HasColumnType($"varchar({ValidationConstants.StringLengths.ShortString})")
            .IsRequired(false);

        builder.Property(e => e.OwnerId)
            .HasColumnType("uuid")
            .IsRequired();

        builder.Property(e => e.UpdatedBy)
            .HasColumnType("uuid")
            .IsRequired(false);

        // Auto-playlist maintenance
        builder.Property(e => e.IsAutoGenerated)
            .HasDefaultValue(false)
            .IsRequired();

        builder.Property(e => e.AutoGroupKind)
            .HasColumnType("integer")
            .IsRequired(false);

        builder.Property(e => e.AutoArtistKey)
            .HasMaxLength(ValidationConstants.StringLengths.MediumString)
            .HasColumnType($"varchar({ValidationConstants.StringLengths.MediumString})")
            .IsRequired(false);

        builder.Property(e => e.AutoAlbumKey)
            .HasMaxLength(ValidationConstants.StringLengths.MediumString)
            .HasColumnType($"varchar({ValidationConstants.StringLengths.MediumString})")
            .IsRequired(false);

        builder.Property(e => e.AutoTagId)
            .HasColumnType("uuid")
            .IsRequired(false);

        builder.Property(e => e.AutoGenreKey)
            .HasMaxLength(ValidationConstants.StringLengths.MediumString)
            .HasColumnType($"varchar({ValidationConstants.StringLengths.MediumString})")
            .IsRequired(false);

        builder.Property(e => e.AutoDecade)
            .HasColumnType("integer")
            .IsRequired(false);

        builder.Property(e => e.LastSyncedAt)
            .HasColumnType("timestamp with time zone")
            .IsRequired(false);

        // DateTime properties
        builder.Property(e => e.CreatedAt)
            .HasColumnType("timestamp with time zone")
            .IsRequired();

        builder.Property(e => e.UpdatedAt)
            .HasColumnType("timestamp with time zone")
            .IsRequired(false);

        builder.Property(e => e.DeletedAt)
            .HasColumnType("timestamp with time zone")
            .IsRequired(false);

        // Relationships
        builder.HasOne(e => e.Owner)
            .WithMany()
            .HasForeignKey(e => e.OwnerId)
            .OnDelete(DeleteBehavior.Restrict);

        builder.HasMany(e => e.PlaylistItems)
            .WithOne(pi => pi.Playlist)
            .HasForeignKey(pi => pi.PlaylistId)
            .OnDelete(DeleteBehavior.Cascade);

        // Indexes
        builder.HasIndex(e => e.OwnerId);
        builder.HasIndex(e => e.CreatedAt);

        // One playlist per grouping per owner. Partial per kind because only the
        // kind's own key columns are set (the rest are NULL, and NULL != NULL).
        // Every filter carries DeletedAt IS NULL: a soft-deleted playlist must
        // not reserve its grouping key, or recreation can never insert.
        // Tag and parent-genre share one index with the kind in the key: two
        // separate HasIndex calls on the same columns fold into a single model
        // index and silently drop one filter.
        builder.HasIndex(e => new { e.OwnerId, e.AutoArtistKey })
            .IsUnique()
            .HasFilter(
                $"\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = {(int)AutoGroupKind.Artist} AND \"DeletedAt\" IS NULL");

        builder.HasIndex(e => new { e.OwnerId, e.AutoArtistKey, e.AutoAlbumKey })
            .IsUnique()
            .HasFilter(
                $"\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = {(int)AutoGroupKind.Album} AND \"DeletedAt\" IS NULL");

        builder.HasIndex(e => new { e.OwnerId, e.AutoGroupKind, e.AutoTagId })
            .IsUnique()
            .HasFilter(
                $"\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" IN ({(int)AutoGroupKind.Tag}, {(int)AutoGroupKind.ParentGenre}) AND \"DeletedAt\" IS NULL");

        builder.HasIndex(e => new { e.OwnerId, e.AutoGenreKey })
            .IsUnique()
            .HasFilter(
                $"\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = {(int)AutoGroupKind.Genre} AND \"DeletedAt\" IS NULL");

        builder.HasIndex(e => new { e.OwnerId, e.AutoDecade })
            .IsUnique()
            .HasFilter(
                $"\"IsAutoGenerated\" = TRUE AND \"AutoGroupKind\" = {(int)AutoGroupKind.Decade} AND \"DeletedAt\" IS NULL");

        builder.ToTable("Playlists");
    }
}