import { AutoGroupKind } from "@/enums/auto-group-kind";

export type CoverLayout = "decade" | "monogram" | "wordmark" | "mood";

export type MoodGlyph =
  | "burst"
  | "sun"
  | "confetti"
  | "horizon"
  | "droplet"
  | "soundhole"
  | "note"
  | "waves";

export interface CoverPalette {
  hue: number;
  hueShift: number;
  saturation: number;
  lightFrom: number;
  lightTo: number;
  ink: string;
  scrimAlpha: number;
  variant: number;
}

export const INK_LIGHT = "#FFFFFF";
export const INK_DARK = "#1C1917";

const MOOD_GLYPHS: Record<string, MoodGlyph> = {
  aggressive: "burst",
  happy: "sun",
  party: "confetti",
  relaxed: "horizon",
  sad: "droplet",
  acoustic: "soundhole",
  instrumental: "note",
  voice: "waves",
};

export const hashSeed = (value: string): number => {
  let hash = 0x811c9dc5;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
};

export const hslToRgb = (h: number, s: number, l: number): [number, number, number] => {
  const saturation = s / 100;
  const lightness = l / 100;
  const k = (n: number) => (n + h / 30) % 12;
  const a = saturation * Math.min(lightness, 1 - lightness);
  const f = (n: number) => lightness - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return [Math.round(f(0) * 255), Math.round(f(8) * 255), Math.round(f(4) * 255)];
};

export const relativeLuminance = (r: number, g: number, b: number): number => {
  const linear = (channel: number) => {
    const c = channel / 255;
    if (c <= 0.03928) {
      return c / 12.92;
    }
    return Math.pow((c + 0.055) / 1.055, 2.4);
  };
  return 0.2126 * linear(r) + 0.7152 * linear(g) + 0.0722 * linear(b);
};

export const contrastRatio = (lumA: number, lumB: number): number => {
  const [hi, lo] = lumA >= lumB ? [lumA, lumB] : [lumB, lumA];
  return (hi + 0.05) / (lo + 0.05);
};

export const coverPalette = (seedId: string, isDark: boolean): CoverPalette => {
  const seed = hashSeed(seedId);
  const hue = seed % 360;
  const hueShift = 28 + ((seed >>> 8) % 32);
  const saturation = 52 + (seed % 12);
  const lightFrom = isDark ? 30 : 66;
  const lightTo = isDark ? 15 : 45;

  const [r1, g1, b1] = hslToRgb(hue, saturation, lightFrom);
  const [r2, g2, b2] = hslToRgb((hue + hueShift) % 360, saturation, lightTo);
  const lumFrom = relativeLuminance(r1, g1, b1);
  const lumTo = relativeLuminance(r2, g2, b2);

  const darkLum = relativeLuminance(28, 25, 23);
  const worstLight = Math.min(contrastRatio(1, lumFrom), contrastRatio(1, lumTo));
  const worstDark = Math.min(contrastRatio(darkLum, lumFrom), contrastRatio(darkLum, lumTo));

  if (worstLight >= worstDark) {
    return {
      hue,
      hueShift,
      saturation,
      lightFrom,
      lightTo,
      ink: INK_LIGHT,
      scrimAlpha: worstLight < 3 ? 0.28 : 0,
      variant: seed % 3,
    };
  }
  return {
    hue,
    hueShift,
    saturation,
    lightFrom,
    lightTo,
    ink: INK_DARK,
    scrimAlpha: worstDark < 3 ? 0.22 : 0,
    variant: seed % 3,
  };
};

export const moodGlyphFor = (name: string): MoodGlyph | null => {
  const key = name.trim().toLowerCase();
  return MOOD_GLYPHS[key] ?? null;
};

export const decadeDigits = (name: string): string | null => {
  const match = name.match(/(\d{4})/);
  return match ? match[1] : null;
};

export const monogramFor = (name: string): string => {
  const letters = name
    .trim()
    .split(/\s+/)
    .filter((word) => word.length > 0)
    .slice(0, 2)
    .map((word) => word.charAt(0))
    .join("");
  if (letters.length > 0) {
    return letters.toUpperCase();
  }
  return "•";
};

export const coverLayoutFor = (
  isAutoGenerated: boolean,
  kind: AutoGroupKind | null | undefined,
  name: string,
  artistAlbumLayout: CoverLayout = "monogram",
): CoverLayout => {
  if (!isAutoGenerated) {
    return "monogram";
  }
  if (kind === AutoGroupKind.Decade) {
    if (decadeDigits(name)) {
      return "decade";
    }
    return "wordmark";
  }
  if (kind === AutoGroupKind.Artist || kind === AutoGroupKind.Album) {
    return artistAlbumLayout;
  }
  if (kind === AutoGroupKind.Tag) {
    if (moodGlyphFor(name)) {
      return "mood";
    }
    return "wordmark";
  }
  if (kind === AutoGroupKind.Genre || kind === AutoGroupKind.ParentGenre) {
    return "wordmark";
  }
  return "monogram";
};
