import type { PlaylistResponse } from "@/api/playlist";

import { AutoGroupKind } from "@/enums/auto-group-kind";
import { PlaylistSort } from "@/enums/playlist-sort";

export type PlaylistOriginFilter = "all" | "auto" | "manual";
export type PlaylistKindFilter = AutoGroupKind | "all";

export interface PlaylistBrowseState {
  page: number;
  origin: PlaylistOriginFilter;
  kind: PlaylistKindFilter;
  sort: PlaylistSort;
}

export const DEFAULT_BROWSE_STATE: PlaylistBrowseState = {
  page: 1,
  origin: "all",
  kind: "all",
  sort: PlaylistSort.Newest,
};

type PlaylistIdentity = Pick<PlaylistResponse, "isAutoGenerated" | "autoGroupKind">;

const KIND_LABELS: Record<AutoGroupKind, string> = {
  [AutoGroupKind.Artist]: "Artist",
  [AutoGroupKind.Album]: "Album",
  [AutoGroupKind.Tag]: "Tag",
  [AutoGroupKind.Genre]: "Genre",
  [AutoGroupKind.ParentGenre]: "Genre",
  [AutoGroupKind.Decade]: "Decade",
};

export const autoGroupKindLabel = (kind: AutoGroupKind | null | undefined): string | null => {
  if (kind === null || kind === undefined) {
    return null;
  }
  return KIND_LABELS[kind] ?? null;
};

export const playlistBadgeLabel = (playlist: PlaylistIdentity): string | null => {
  if (!playlist.isAutoGenerated) {
    return null;
  }
  const kindLabel = autoGroupKindLabel(playlist.autoGroupKind);
  if (kindLabel) {
    return `Auto · ${kindLabel}`;
  }
  return "Auto";
};

const firstQueryValue = (value: unknown): string | null => {
  if (typeof value === "string") {
    return value;
  }
  if (Array.isArray(value) && typeof value[0] === "string") {
    return value[0];
  }
  return null;
};

const parsePage = (value: unknown): number => {
  const raw = firstQueryValue(value);
  if (raw === null) {
    return 1;
  }
  const parsed = Number.parseInt(raw, 10);
  if (!Number.isInteger(parsed) || parsed < 1) {
    return 1;
  }
  return parsed;
};

const parseOrigin = (value: unknown): PlaylistOriginFilter => {
  const raw = firstQueryValue(value);
  if (raw === "auto" || raw === "manual") {
    return raw;
  }
  return "all";
};

const parseKind = (value: unknown): PlaylistKindFilter => {
  const raw = firstQueryValue(value);
  if (raw === null || raw === "all") {
    return "all";
  }
  const parsed = Number.parseInt(raw, 10);
  const kinds = [
    AutoGroupKind.Artist,
    AutoGroupKind.Album,
    AutoGroupKind.Tag,
    AutoGroupKind.Genre,
    AutoGroupKind.ParentGenre,
    AutoGroupKind.Decade,
  ];
  if (kinds.includes(parsed as AutoGroupKind)) {
    return parsed as AutoGroupKind;
  }
  return "all";
};

const parseSort = (value: unknown): PlaylistSort => {
  const raw = firstQueryValue(value);
  if (raw === null) {
    return PlaylistSort.Newest;
  }
  const parsed = Number.parseInt(raw, 10);
  if (
    parsed === PlaylistSort.Newest ||
    parsed === PlaylistSort.Name ||
    parsed === PlaylistSort.TrackCount
  ) {
    return parsed;
  }
  return PlaylistSort.Newest;
};

export const parsePlaylistBrowseQuery = (query: Record<string, unknown>): PlaylistBrowseState => ({
  page: parsePage(query.page),
  origin: parseOrigin(query.origin),
  kind: parseKind(query.kind),
  sort: parseSort(query.sort),
});

export const playlistBrowseQuery = (state: PlaylistBrowseState): Record<string, string> => {
  const query: Record<string, string> = {};
  if (state.page > 1) {
    query.page = String(state.page);
  }
  if (state.origin !== "all") {
    query.origin = state.origin;
  }
  if (state.kind !== "all") {
    query.kind = String(state.kind);
  }
  if (state.sort !== PlaylistSort.Newest) {
    query.sort = String(state.sort);
  }
  return query;
};
