using System.Linq.Expressions;
using Alexandria.Common.Repositories;
using Alexandria.Data.Context;
using Alexandria.Data.Models;
using Alexandria.Data.Models.Enumerators;
using Alexandria.Dto.Files;
using Alexandria.Dto.Files.Streaming;
using Alexandria.Dto.Files.Streaming.Playlist;
using Microsoft.EntityFrameworkCore;

namespace Alexandria.Repositories;

public class PlaylistRepository(AlexandriaDbContext context) : IPlaylistRepository
{
    private readonly DbSet<Playlist> _playlists = context.Playlists;
    private readonly DbSet<PlaylistItem> _playlistItems = context.PlaylistItems;

    public async Task<Playlist?> GetByIdAsync(Guid id, CancellationToken ct = default)
    {
        return await _playlists
            .Where(p => p.DeletedAt == null)
            .FirstOrDefaultAsync(p => p.Id == id, ct);
    }

    public async Task<Playlist> CreateAsync(Playlist entity, CancellationToken ct = default)
    {
        var now = DateTime.UtcNow;
        entity.CreatedAt = now;
        entity.UpdatedAt = null;
        entity.DeletedAt = null;

        if (entity.PlaylistItems is not null)
        {
            foreach (var item in entity.PlaylistItems)
                item.CreatedAt = now;
        }

        await _playlists.AddAsync(entity, ct);
        await context.SaveChangesAsync(ct);
        return entity;
    }

    public async Task<Playlist> UpdateAsync(Playlist entity, CancellationToken ct = default)
    {
        entity.UpdatedAt = DateTime.UtcNow;
        _playlists.Update(entity);
        await context.SaveChangesAsync(ct);
        return entity;
    }

    public async Task<PlaylistDto?> GetSummaryAsync(Guid id, Guid userId, CancellationToken ct = default)
    {
        return await _playlists
            .Where(p => p.Id == id && p.OwnerId == userId && p.DeletedAt == null)
            .Select(p => new PlaylistDto
            {
                Id = p.Id,
                Name = p.Name,
                Description = p.Description,
                HasCover = p.HasCover,
                AmbientTheme = p.AmbientTheme,
                ItemCount = p.PlaylistItems!.Count(i => i.DeletedAt == null),
                IsAutoGenerated = p.IsAutoGenerated,
                AutoGroupKind = p.AutoGroupKind,
                CreatedAt = p.CreatedAt,
                UpdatedAt = p.UpdatedAt
            })
            .FirstOrDefaultAsync(ct);
    }

    public async Task<PlaylistDetailDto?> GetWithItemsAsync(Guid id, Guid userId, CancellationToken ct = default)
    {
        return await _playlists
            .Where(p => p.Id == id && p.OwnerId == userId && p.DeletedAt == null)
            .Select(p => new PlaylistDetailDto
            {
                Id = p.Id,
                Name = p.Name,
                Description = p.Description,
                HasCover = p.HasCover,
                AmbientTheme = p.AmbientTheme,
                IsAutoGenerated = p.IsAutoGenerated,
                AutoGroupKind = p.AutoGroupKind,
                CreatedAt = p.CreatedAt,
                UpdatedAt = p.UpdatedAt,
                Items = p.PlaylistItems!
                    .Where(i => i.DeletedAt == null)
                    .OrderBy(i => i.Position)
                    .ThenBy(i => i.Id)
                    .Select(i => new PlaylistItemDto
                    {
                        Id = i.Id,
                        Position = i.Position,
                        TranspilationJobId = i.TranspilationJobId,
                        FileId = i.TranspilationJob!.FileVersion.FileId,
                        FileName = i.TranspilationJob!.FileVersion.File.Name,
                        MimeType = i.TranspilationJob!.FileVersion.File.MimeType,
                        SegmentPrefix = i.TranspilationJob!.SegmentPrefix,
                        CreatedAt = i.CreatedAt,
                        Representations = i.TranspilationJob!.Representations
                            .Where(r => r.DeletedAt == null)
                            .Select(r => new StreamingRepresentationDto
                            {
                                Id = r.Id,
                                Codec = r.Codec,
                                Width = r.Width,
                                Height = r.Height,
                                BitrateKbps = r.BitrateKbps,
                                Status = r.Status
                            })
                            .ToList()
                    })
                    .ToList()
            })
            .FirstOrDefaultAsync(ct);
    }

    public async Task<PaginatedResult<PlaylistDto>> GetByUserAsync(
        Guid userId,
        int page,
        int pageSize,
        bool? isAutoGenerated = null,
        AutoGroupKind? kind = null,
        PlaylistSort sort = PlaylistSort.Newest,
        CancellationToken ct = default)
    {
        var query = _playlists
            .Where(p => p.OwnerId == userId && p.DeletedAt == null);

        if (isAutoGenerated.HasValue)
            query = query.Where(p => p.IsAutoGenerated == isAutoGenerated.Value);

        if (kind.HasValue)
            query = query.Where(p => p.IsAutoGenerated && p.AutoGroupKind == kind.Value);

        var count = await query.CountAsync(ct);

        if (sort == PlaylistSort.Name)
            query = query.OrderBy(p => p.Name).ThenByDescending(p => p.CreatedAt);
        else if (sort == PlaylistSort.TrackCount)
            query = query
                .OrderByDescending(p => p.PlaylistItems!.Count(i => i.DeletedAt == null))
                .ThenBy(p => p.Name);
        else
            query = query.OrderByDescending(p => p.CreatedAt);

        var items = await query
            .Skip((page - 1) * pageSize)
            .Take(pageSize)
            .Select(p => new PlaylistDto
            {
                Id = p.Id,
                Name = p.Name,
                Description = p.Description,
                HasCover = p.HasCover,
                AmbientTheme = p.AmbientTheme,
                ItemCount = p.PlaylistItems!.Count(i => i.DeletedAt == null),
                IsAutoGenerated = p.IsAutoGenerated,
                AutoGroupKind = p.AutoGroupKind,
                CreatedAt = p.CreatedAt,
                UpdatedAt = p.UpdatedAt
            })
            .ToListAsync(ct);

        return new PaginatedResult<PlaylistDto>
        {
            Items = items,
            CurrentPage = page,
            PageSize = pageSize,
            TotalCount = count,
            TotalPages = (int)Math.Ceiling(count / (double)pageSize)
        };
    }

    public async Task SoftDeleteAsync(Guid playlistId, Guid userId, CancellationToken ct = default)
    {
        var now = DateTime.UtcNow;

        await _playlistItems
            .Where(i => i.PlaylistId == playlistId && i.DeletedAt == null)
            .ExecuteUpdateAsync(s => s
                .SetProperty(i => i.DeletedAt, now)
                .SetProperty(i => i.UpdatedAt, now)
                .SetProperty(i => i.UpdatedBy, userId), ct);

        await _playlists
            .Where(p => p.Id == playlistId && p.OwnerId == userId && p.DeletedAt == null)
            .ExecuteUpdateAsync(s => s
                .SetProperty(p => p.DeletedAt, now)
                .SetProperty(p => p.UpdatedAt, now)
                .SetProperty(p => p.UpdatedBy, userId), ct);
    }

    public async Task ReorderItemsAsync(
        Guid playlistId, Guid[] orderedItemIds, CancellationToken ct = default)
    {
        var items = await _playlistItems
            .Where(i => i.PlaylistId == playlistId && i.DeletedAt == null)
            .ToListAsync(ct);

        var positionMap = orderedItemIds
            .Select((id, index) => (id, index))
            .ToDictionary(x => x.id, x => x.index);

        var now = DateTime.UtcNow;
        foreach (var item in items)
        {
            if (!positionMap.TryGetValue(item.Id, out var position))
                continue;

            item.Position = position;
            item.UpdatedAt = now;
        }

        await context.SaveChangesAsync(ct);
    }

    public async Task<PlaylistItemDto> AddItemAsync(PlaylistItem item, CancellationToken ct = default)
    {
        // Manually re-adding a user-removed track resurrects the tombstone (flag
        // cleared) instead of duplicating the row. A live row means the user wants
        // the track twice, so that still inserts.
        var tombstone = await _playlistItems
            .Where(i => i.PlaylistId == item.PlaylistId
                        && i.TranspilationJobId == item.TranspilationJobId
                        && i.DeletedAt != null)
            .OrderByDescending(i => i.DeletedAt)
            .FirstOrDefaultAsync(ct);

        var hasLiveRow = await _playlistItems
            .AnyAsync(i => i.PlaylistId == item.PlaylistId
                           && i.TranspilationJobId == item.TranspilationJobId
                           && i.DeletedAt == null, ct);

        if (tombstone is not null && !hasLiveRow)
        {
            var maxPosition = await _playlistItems
                .Where(i => i.PlaylistId == item.PlaylistId && i.DeletedAt == null)
                .MaxAsync(i => (int?)i.Position, ct) ?? -1;

            tombstone.DeletedAt = null;
            tombstone.UpdatedAt = DateTime.UtcNow;
            tombstone.UpdatedBy = item.UpdatedBy;
            tombstone.RemovedByUser = false;
            tombstone.Position = maxPosition + 1;
            await context.SaveChangesAsync(ct);
            item = tombstone;
        }
        else
        {
            var maxPosition = await _playlistItems
                .Where(i => i.PlaylistId == item.PlaylistId && i.DeletedAt == null)
                .MaxAsync(i => (int?)i.Position, ct) ?? -1;

            item.Position = maxPosition + 1;
            item.CreatedAt = DateTime.UtcNow;

            await _playlistItems.AddAsync(item, ct);
            await context.SaveChangesAsync(ct);
        }

        return await _playlistItems
            .Where(i => i.Id == item.Id)
            .Select(i => new PlaylistItemDto
            {
                Id = i.Id,
                Position = i.Position,
                TranspilationJobId = i.TranspilationJobId,
                FileId = i.TranspilationJob!.FileVersion.FileId,
                FileName = i.TranspilationJob!.FileVersion.File.Name,
                MimeType = i.TranspilationJob!.FileVersion.File.MimeType,
                SegmentPrefix = i.TranspilationJob!.SegmentPrefix,
                CreatedAt = i.CreatedAt,
                Representations = i.TranspilationJob!.Representations
                    .Where(r => r.DeletedAt == null)
                    .Select(r => new StreamingRepresentationDto
                    {
                        Id = r.Id,
                        Codec = r.Codec,
                        Width = r.Width,
                        Height = r.Height,
                        BitrateKbps = r.BitrateKbps,
                        Status = r.Status
                    })
                    .ToList()
            })
            .FirstAsync(ct);
    }

    public async Task RemoveItemAsync(
        Guid playlistId, Guid itemId, Guid userId, CancellationToken ct = default)
    {
        var now = DateTime.UtcNow;

        // User removal through the normal API. The flag is what keeps the
        // reconciler from silently re-adding the track on the next sync.
        await _playlistItems
            .Where(i => i.Id == itemId && i.PlaylistId == playlistId && i.DeletedAt == null)
            .ExecuteUpdateAsync(s => s
                .SetProperty(i => i.DeletedAt, now)
                .SetProperty(i => i.UpdatedAt, now)
                .SetProperty(i => i.UpdatedBy, userId)
                .SetProperty(i => i.RemovedByUser, true), ct);
    }

    public async Task<bool> IsOwnerAsync(Guid playlistId, Guid userId, CancellationToken ct = default)
    {
        return await _playlists
            .AnyAsync(p => p.Id == playlistId && p.OwnerId == userId && p.DeletedAt == null, ct);
    }

    public async Task<Playlist?> GetAutoPlaylistAsync(
        Guid ownerId,
        AutoGroupKind kind,
        string? artistKey,
        string? albumKey,
        Guid? tagId,
        string? genreKey,
        int? decade,
        CancellationToken ct = default)
    {
        return await _playlists
            .Where(p => p.OwnerId == ownerId
                        && p.DeletedAt == null
                        && p.IsAutoGenerated
                        && p.AutoGroupKind == kind
                        && p.AutoArtistKey == artistKey
                        && p.AutoAlbumKey == albumKey
                        && p.AutoTagId == tagId
                        && p.AutoGenreKey == genreKey
                        && p.AutoDecade == decade)
            .FirstOrDefaultAsync(ct);
    }

    public async Task<IReadOnlyList<PlaylistItemState>> GetItemsIncludingDeletedAsync(
        Guid playlistId, CancellationToken ct = default)
    {
        return await _playlistItems
            .Where(i => i.PlaylistId == playlistId)
            .OrderBy(i => i.Id)
            .Select(i => new PlaylistItemState(
                i.Id,
                i.TranspilationJobId,
                i.DeletedAt != null,
                i.RemovedByUser,
                i.DeletedAt))
            .ToListAsync(ct);
    }

    public async Task<IReadOnlyList<Guid>> GetOwnerAutoPlaylistIdsForFileAsync(
        Guid ownerId, Guid fileId, CancellationToken ct = default)
    {
        return await _playlistItems
            .Where(i => i.DeletedAt == null
                        && i.Playlist.DeletedAt == null
                        && i.Playlist.OwnerId == ownerId
                        && i.Playlist.IsAutoGenerated
                        && i.TranspilationJob.FileVersion.FileId == fileId)
            .Select(i => i.PlaylistId)
            .Distinct()
            .ToListAsync(ct);
    }

    public async Task<PlaylistItem> AddAutoItemAsync(
        Guid playlistId, Guid transpilationJobId, Guid ownerId, CancellationToken ct = default)
    {
        var maxPosition = await _playlistItems
            .Where(i => i.PlaylistId == playlistId && i.DeletedAt == null)
            .MaxAsync(i => (int?)i.Position, ct) ?? -1;

        var item = new PlaylistItem
        {
            Id = Guid.NewGuid(),
            PlaylistId = playlistId,
            TranspilationJobId = transpilationJobId,
            Position = maxPosition + 1,
            CreatedAt = DateTime.UtcNow,
            UpdatedBy = ownerId,
        };

        await _playlistItems.AddAsync(item, ct);
        await context.SaveChangesAsync(ct);
        return item;
    }

    public async Task ReviveAutoItemAsync(Guid itemId, CancellationToken ct = default)
    {
        var item = await _playlistItems
            .Where(i => i.Id == itemId)
            .Select(i => new { i.PlaylistId, i.Position })
            .FirstOrDefaultAsync(ct);

        if (item is null)
            return;

        // Keep the original position only when still free, else append, so two
        // live rows never share a position.
        var occupied = await _playlistItems
            .AnyAsync(i => i.PlaylistId == item.PlaylistId
                           && i.Id != itemId
                           && i.DeletedAt == null
                           && i.Position == item.Position, ct);

        var position = item.Position;
        if (occupied)
        {
            position = await _playlistItems
                .Where(i => i.PlaylistId == item.PlaylistId && i.DeletedAt == null)
                .MaxAsync(i => (int?)i.Position, ct) ?? -1;
            position++;
        }

        await _playlistItems
            .Where(i => i.Id == itemId)
            .ExecuteUpdateAsync(s => s
                .SetProperty(i => i.DeletedAt, (DateTime?)null)
                .SetProperty(i => i.Position, position)
                .SetProperty(i => i.UpdatedAt, DateTime.UtcNow), ct);
    }

    public async Task RemoveAutoItemAsync(Guid itemId, Guid ownerId, CancellationToken ct = default)
    {
        var now = DateTime.UtcNow;

        await _playlistItems
            .Where(i => i.Id == itemId && i.DeletedAt == null)
            .ExecuteUpdateAsync(s => s
                .SetProperty(i => i.DeletedAt, now)
                .SetProperty(i => i.UpdatedAt, now)
                .SetProperty(i => i.UpdatedBy, ownerId), ct);
    }

    public async Task TouchAutoPlaylistAsync(Guid playlistId, CancellationToken ct = default)
    {
        await _playlists
            .Where(p => p.Id == playlistId)
            .ExecuteUpdateAsync(s => s
                .SetProperty(p => p.LastSyncedAt, DateTime.UtcNow), ct);
    }

    public async Task<IReadOnlyList<Guid>> GetSupersededGenrePlaylistIdsAsync(
        Guid ownerId, CancellationToken ct = default)
    {
        return await _playlists
            .Where(p => p.OwnerId == ownerId
                        && p.DeletedAt == null
                        && p.IsAutoGenerated
                        && p.AutoGroupKind == AutoGroupKind.Tag
                        && p.AutoTagId.HasValue
                        && context.Tags.Any(t =>
                            t.Id == p.AutoTagId!.Value
                            && t.DeletedAt == null
                            && t.Facet == TagFacet.Genre))
            .Select(p => p.Id)
            .ToListAsync(ct);
    }

    public async Task<IReadOnlyList<Guid>> GetSyncOwnerIdsAsync(CancellationToken ct = default)
    {
        // Owners with live files UNION owners with live automatic playlists,
        // so deleting the last live file cannot orphan that owner's lists.
        var fileOwners = context.Files
            .Where(f => f.DeletedAt == null)
            .Select(f => f.OwnerId);
        var playlistOwners = _playlists
            .Where(p => p.DeletedAt == null && p.IsAutoGenerated)
            .Select(p => p.OwnerId);

        return await fileOwners.Union(playlistOwners).Distinct().ToListAsync(ct);
    }

    public async Task<IReadOnlyList<Playlist>> GetOwnerAutoPlaylistsAsync(
        Guid ownerId, CancellationToken ct = default)
    {
        return await _playlists
            .Where(p => p.OwnerId == ownerId && p.DeletedAt == null && p.IsAutoGenerated)
            .ToListAsync(ct);
    }

    // IRepository<Playlist> base members

    public async Task<IEnumerable<Playlist>> GetAllAsync(CancellationToken ct = default)
        => await _playlists.Where(p => p.DeletedAt == null).ToListAsync(ct);

    public async Task<IEnumerable<Playlist>> FindAsync(
        Expression<Func<Playlist, bool>> predicate, CancellationToken ct = default)
        => await _playlists.Where(p => p.DeletedAt == null).Where(predicate).ToListAsync(ct);

    public async Task<Playlist?> FirstOrDefaultAsync(
        Expression<Func<Playlist, bool>> predicate, CancellationToken ct = default)
        => await _playlists.Where(p => p.DeletedAt == null).FirstOrDefaultAsync(predicate, ct);

    public async Task<Playlist> AddAsync(Playlist entity, CancellationToken ct = default)
    {
        entity.CreatedAt = DateTime.UtcNow;
        var result = await _playlists.AddAsync(entity, ct);
        await context.SaveChangesAsync(ct);
        return result.Entity;
    }

    public async Task<IEnumerable<Playlist>> AddRangeAsync(
        IEnumerable<Playlist> entities, CancellationToken ct = default)
    {
        var list = entities.ToList();
        var now = DateTime.UtcNow;
        foreach (var e in list) e.CreatedAt = now;
        await _playlists.AddRangeAsync(list, ct);
        await context.SaveChangesAsync(ct);
        return list;
    }

    public void Update(Playlist entity)
    {
        entity.UpdatedAt = DateTime.UtcNow;
        _playlists.Update(entity);
    }

    public void Remove(Playlist entity)
    {
        entity.DeletedAt = DateTime.UtcNow;
        entity.UpdatedAt = DateTime.UtcNow;
        _playlists.Update(entity);
    }

    public void RemoveRange(IEnumerable<Playlist> entities)
    {
        var now = DateTime.UtcNow;
        var playlists = entities as Playlist[] ?? entities.ToArray();
        foreach (var e in playlists)
        {
            e.DeletedAt = now;
            e.UpdatedAt = now;
        }

        _playlists.UpdateRange(playlists);
    }

    public async Task<int> CountAsync(
        Expression<Func<Playlist, bool>>? predicate = null, CancellationToken ct = default)
    {
        var query = _playlists.Where(p => p.DeletedAt == null);
        if (predicate != null) query = query.Where(predicate);
        return await query.CountAsync(ct);
    }

    public async Task<bool> ExistsAsync(
        Expression<Func<Playlist, bool>> predicate, CancellationToken ct = default)
        => await _playlists.Where(p => p.DeletedAt == null).AnyAsync(predicate, ct);
}