using Alexandria.Data.Models.Enumerators;

namespace Alexandria.Data.Models;

public class Playlist : IBase
{
    public Guid Id { get; set; }
    public required string Name { get; set; }
    public string? Description { get; set; }
    public bool HasCover { get; set; } = false;
    public string? AmbientTheme { get; set; }

    public Guid OwnerId { get; set; }
    public ApplicationUser? Owner { get; set; }
    public ICollection<PlaylistItem>? PlaylistItems { get; set; }

    /// <summary>
    /// True when a background worker maintains membership. Manual playlists are
    /// always false; users can still rename or delete auto playlists normally.
    /// </summary>
    public bool IsAutoGenerated { get; set; } = false;

    public AutoGroupKind? AutoGroupKind { get; set; }

    /// <summary>Normalized artist key (Artist and Album kinds).</summary>
    public string? AutoArtistKey { get; set; }

    /// <summary>Normalized album key (Album kind only).</summary>
    public string? AutoAlbumKey { get; set; }

    /// <summary>Source tag (Tag kind only).</summary>
    public Guid? AutoTagId { get; set; }

    /// <summary>Normalized free-text genre key (Genre fallback kind only).</summary>
    public string? AutoGenreKey { get; set; }

    /// <summary>Decade start year, e.g. 2010 (Decade kind only).</summary>
    public int? AutoDecade { get; set; }

    public DateTime? LastSyncedAt { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public DateTime? DeletedAt { get; set; }
    public Guid? UpdatedBy { get; set; }
}