import type { Plugin } from "vite";

// vite-plugin-iconify-subset.ts
import { getIcons } from "@iconify/utils";

// Your icon lists, centralised here
const ICON_SUBSETS: Record<string, string[]> = {
  formkit: ["zip"],
  heroicons: [
    "archive-box",
    "arrow-path",
    "arrow-right",
    "arrow-right-on-rectangle",
    "book-open",
    "chart-bar",
    "check-16-solid",
    "clock",
    "cog-6-tooth",
    "command-line",
    "chevron-right",
    "folder",
    "folder-open",
    "home",
    "plus",
    "scale",
    "shield-check",
    "tag",
    "trash",
    "user",
    "user-circle",
    "users",
    "x-mark",
    "bookmark",
    "document-text",
    "star",
    "heart",
    "flag",
    "check-circle",
    "exclamation-triangle",
    "briefcase",
    "calendar",
    "magnifying-glass",
    "plus-circle",
    "minus-circle",
    "pencil-square",
    "link",
    "lock-closed",
    "lock-open",
    "arrow-down-tray",
    "arrow-up-tray",
    "bell",
    "chat-bubble-left-right",
    "photo",
    "video-camera",
    "map-pin",
  ],
  lucide: [
    "activity",
    "alert-circle",
    "archive",
    "arrow-down",
    "arrow-left",
    "arrow-right",
    "arrow-right-on-rectangle",
    "arrow-up",
    "arrow-up-down",
    "calendar",
    "calendar-clock",
    "calendar-days",
    "calendar-plus",
    "calendar-range",
    "calendar-x",
    "check",
    "check-circle",
    "chevron-down",
    "chevron-left",
    "chevron-right",
    "chevron-up",
    "circle",
    "clipboard-check",
    "copy",
    "edit",
    "ellipsis-vertical",
    "eye",
    "eye-off",
    "file",
    "file-archive",
    "file-clock",
    "file-plus",
    "files",
    "fingerprint",
    "folder",
    "folder-open",
    "folder-up",
    "folder-x",
    "hard-drive",
    "hash",
    "image",
    "info",
    "layout-grid",
    "list",
    "loader-circle",
    "lock",
    "lock-keyhole",
    "lock-open",
    "log-in",
    "log-out",
    "mail",
    "package-open",
    "palette",
    "pencil",
    "pencil-line",
    "plus",
    "plus-circle",
    "refresh-cw",
    "rocket",
    "rotate-ccw",
    "save",
    "search",
    "shield-check",
    "sliders-horizontal",
    "tag",
    "tag-off",
    "tags",
    "text-cursor-input",
    "trash",
    "trash-2",
    "triangle-alert",
    "upload",
    "user",
    "user-check",
    "user-plus",
    "user-search",
    "users",
    "x",
    "x-circle",
    "circle-alert",
    "chevrons-left",
    "chevrons-right",
    "copy-check",
    "moon",
    "grip-vertical",
    "ellipsis",
    "circle-x",
    "arrow-up-right",
    "sun",
    "menu",
    "minus",
    "panel-left-close",
    "panel-left-open",
    "square",
    "circle-check",
    "monitor",
    "lightbulb",
  ],
  "material-symbols": ["keyboard-outline-rounded", "vitals"],
  mdi: [
    "account",
    "account-circle-outline",
    "account-group-outline",
    "account-multiple",
    "account-outline",
    "alert-circle",
    "alert-circle-outline",
    "archive-outline",
    "arrow-expand",
    "arrow-left",
    "arrow-right",
    "arrow-right-thin",
    "bell-alert",
    "bell-ring",
    "bell-off",
    "bell-outline",
    "book-open-page-variant-outline",
    "book-open-variant",
    "chart-donut",
    "chart-pie",
    "check",
    "check-circle",
    "check-circle-outline",
    "chevron-down",
    "chevron-right",
    "clock-outline",
    "close-circle",
    "cloud-upload-outline",
    "cog",
    "cog-outline",
    "cpu-64-bit",
    "delete-clock",
    "delete-outline",
    "dots-horizontal",
    "download",
    "folder-move",
    "content-copy",
    "share-variant",
    "folder-copy",
    "pencil",
    "delete",
    "eye-off-outline",
    "eye-outline",
    "file",
    "file-document",
    "file-outline",
    "folder",
    "folder-arrow-up",
    "folder-open",
    "folder-open-outline",
    "folder-outline",
    "folder-plus",
    "folder-upload-outline",
    "format-list-checks",
    "github",
    "harddisk",
    "heart-pulse",
    "help-circle",
    "history",
    "identifier",
    "image-outline",
    "keyboard-off-outline",
    "keyboard-outline",
    "lightning-bolt",
    "loading",
    "lock-outline",
    "lock-reset",
    "magnify",
    "map-marker-radius-outline",
    "memory",
    "minus",
    "palette-outline",
    "pause",
    "play",
    "plus",
    "recycle",
    "refresh",
    "rocket-launch-outline",
    "restore",
    "scale",
    "server",
    "shape-outline",
    "shield-account-outline",
    "shield-crown-outline",
    "sort-ascending",
    "sort-descending",
    "source-branch",
    "tab",
    "tag",
    "tag-multiple-outline",
    "tag-outline",
    "timer-outline",
    "timer-sand",
    "trash-can-outline",
    "tune-variant",
    "tune-vertical",
    "update",
    "upload",
    "upload-outline",
    "view-grid",
    "view-grid-outline",
    "view-list",
    "view-list-outline",
    "volume-high",
    "volume-medium",
    "volume-off",
    "file-pdf-box",
    "file-word",
    "file-document-outline",
    "file-excel",
    "file-delimited-outline",
    "file-powerpoint",
    "file-image",
    "file-video",
    "file-music",
    "folder-zip",
    "language-javascript",
    "language-typescript",
    "vuejs",
    "react",
    "close",
    "folder-remove-outline",
    "language-python",
    "language-java",
    "language-html5",
    "language-css3",
    "code-json",
  ],
  "mdi-light": ["file", "material-symbols:keyboard-outline-rounded"],
};

export const iconifySubsetPlugin = (): Plugin => {
  const virtualModuleId = "virtual:iconify-subset";
  const resolvedId = "\0" + virtualModuleId;

  return {
    async load(id) {
      if (id !== resolvedId) return;

      const collections: Record<string, unknown> = {};

      for (const [prefix, names] of Object.entries(ICON_SUBSETS)) {
        // Dynamic import — bundler sees this at build time, not shipped to client
        const full = await import(`@iconify-json/${prefix}/icons.json`, {
          with: { type: "json" },
        });
        collections[prefix] = getIcons(full.default, names);
      }

      return `export default ${JSON.stringify(collections)}`;
    },
    name: "iconify-subset",
    resolveId(id) {
      if (id === virtualModuleId) return resolvedId;
    },
  };
};
